"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DoubleFunction = void 0;
exports.createDoubleFunctionProxy = createDoubleFunctionProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link DoubleFunction} interface.
 * All required methods in {@link DoubleFunctionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDoubleFunctionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.function.DoubleFunction', methods, opts);
}
/**
 * Class java.util.function.DoubleFunction.
 *
 * This actually imports the java class for further use.
 * The class {@link DoubleFunctionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DoubleFunction extends (0, java_bridge_1.importClass)('java.util.function.DoubleFunction') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.DoubleFunction = DoubleFunction;
exports.default = DoubleFunction;
