"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RandomGenerator = void 0;
exports.createRandomGeneratorProxy = createRandomGeneratorProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link RandomGenerator} interface.
 * All required methods in {@link RandomGeneratorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createRandomGeneratorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.random.RandomGenerator', methods, opts);
}
/**
 * Class java.util.random.RandomGenerator.
 *
 * This actually imports the java class for further use.
 * The class {@link RandomGeneratorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class RandomGenerator extends (0, java_bridge_1.importClass)('java.util.random.RandomGenerator') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.RandomGenerator = RandomGenerator;
exports.default = RandomGenerator;
