import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Float as java_lang_Float } from "./../../lang/Float";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Long as java_lang_Long } from "./../../lang/Long";
import { Double as java_lang_Double } from "./../../lang/Double";
import { LongStream as java_util_stream_LongStream } from "./../stream/LongStream";
import { IntStream as java_util_stream_IntStream } from "./../stream/IntStream";
import { DoubleStream as java_util_stream_DoubleStream } from "./../stream/DoubleStream";
/**
 * This class just defines types, you should import {@link RandomGenerator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RandomGeneratorClass extends JavaClass {
    /**
     * @return original return type: 'float'
     */
    nextFloat(): Promise<number>;
    /**
     * @return original return type: 'float'
     */
    nextFloatSync(): number;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloat(var0: java_lang_Float | number): Promise<number>;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloatSync(var0: java_lang_Float | number): number;
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloat(var0: java_lang_Float | number, var1: java_lang_Float | number): Promise<number>;
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloatSync(var0: java_lang_Float | number, var1: java_lang_Float | number): number;
    /**
     * @return original return type: 'boolean'
     */
    isDeprecated(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isDeprecatedSync(): boolean;
    /**
     * @return original return type: 'java.util.random.RandomGenerator'
     */
    static getDefault(): Promise<RandomGenerator | null>;
    /**
     * @return original return type: 'java.util.random.RandomGenerator'
     */
    static getDefaultSync(): RandomGenerator | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'int'
     */
    nextInt(var0: java_lang_Integer | number): Promise<number>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'int'
     */
    nextIntSync(var0: java_lang_Integer | number): number;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    nextInt(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<number>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    nextIntSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): number;
    /**
     * @return original return type: 'int'
     */
    nextInt(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    nextIntSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    nextLong(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    nextLongSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): number;
    /**
     * @return original return type: 'long'
     */
    nextLong(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    nextLongSync(): number;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    nextLong(var0: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    nextLongSync(var0: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'double'
     */
    nextDouble(var0: java_lang_Double | number): Promise<number>;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'double'
     */
    nextDoubleSync(var0: java_lang_Double | number): number;
    /**
     * @return original return type: 'double'
     */
    nextDouble(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    nextDoubleSync(): number;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextDouble(var0: java_lang_Double | number, var1: java_lang_Double | number): Promise<number>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextDoubleSync(var0: java_lang_Double | number, var1: java_lang_Double | number): number;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextGaussian(var0: java_lang_Double | number, var1: java_lang_Double | number): Promise<number>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextGaussianSync(var0: java_lang_Double | number, var1: java_lang_Double | number): number;
    /**
     * @return original return type: 'double'
     */
    nextGaussian(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    nextGaussianSync(): number;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    nextBytes(var0: Buffer | null): Promise<void>;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    nextBytesSync(var0: Buffer | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): Promise<java_util_stream_LongStream | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longsSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<java_util_stream_LongStream | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longsSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs(): Promise<java_util_stream_LongStream | null>;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    longsSync(): java_util_stream_LongStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs(var0: java_lang_Long | bigint | number): Promise<java_util_stream_LongStream | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longsSync(var0: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @return original return type: 'double'
     */
    nextExponential(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    nextExponentialSync(): number;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<java_util_stream_IntStream | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    intsSync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): java_util_stream_IntStream | null;
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints(): Promise<java_util_stream_IntStream | null>;
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    intsSync(): java_util_stream_IntStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints(var0: java_lang_Long | bigint | number): Promise<java_util_stream_IntStream | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.IntStream'
     */
    intsSync(var0: java_lang_Long | bigint | number): java_util_stream_IntStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<java_util_stream_IntStream | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    intsSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_util_stream_IntStream | null;
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles(): Promise<java_util_stream_DoubleStream | null>;
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doublesSync(): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles(var0: java_lang_Long | bigint | number, var1: java_lang_Double | number, var2: java_lang_Double | number): Promise<java_util_stream_DoubleStream | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doublesSync(var0: java_lang_Long | bigint | number, var1: java_lang_Double | number, var2: java_lang_Double | number): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles(var0: java_lang_Double | number, var1: java_lang_Double | number): Promise<java_util_stream_DoubleStream | null>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doublesSync(var0: java_lang_Double | number, var1: java_lang_Double | number): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles(var0: java_lang_Long | bigint | number): Promise<java_util_stream_DoubleStream | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doublesSync(var0: java_lang_Long | bigint | number): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.random.RandomGenerator'
     */
    static of(var0: string | null): Promise<RandomGenerator | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.random.RandomGenerator'
     */
    static ofSync(var0: string | null): RandomGenerator | null;
    /**
     * @return original return type: 'boolean'
     */
    nextBoolean(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    nextBooleanSync(): boolean;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createRandomGeneratorProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface RandomGeneratorInterface {
    /**
     * @return original return type: 'float'
     */
    nextFloat?(): number;
    /**
     * @param var0 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloat?(var0: java_lang_Float | number): number;
    /**
     * @param var0 original type: 'float'
     * @param var1 original type: 'float'
     * @return original return type: 'float'
     */
    nextFloat?(var0: java_lang_Float | number, var1: java_lang_Float | number): number;
    /**
     * @return original return type: 'boolean'
     */
    isDeprecated?(): boolean;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'int'
     */
    nextInt?(var0: java_lang_Integer | number): number;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'int'
     */
    nextInt?(var0: java_lang_Integer | number, var1: java_lang_Integer | number): number;
    /**
     * @return original return type: 'int'
     */
    nextInt?(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    nextLong?(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): number;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @return original return type: 'long'
     */
    nextLong?(): number;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'long'
     */
    nextLong?(var0: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'double'
     */
    nextDouble?(var0: java_lang_Double | number): number;
    /**
     * @return original return type: 'double'
     */
    nextDouble?(): number;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextDouble?(var0: java_lang_Double | number, var1: java_lang_Double | number): number;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'double'
     */
    nextGaussian?(var0: java_lang_Double | number, var1: java_lang_Double | number): number;
    /**
     * @return original return type: 'double'
     */
    nextGaussian?(): number;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    nextBytes?(var0: Buffer | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs?(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs?(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs?(): java_util_stream_LongStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.LongStream'
     */
    longs?(var0: java_lang_Long | bigint | number): java_util_stream_LongStream | null;
    /**
     * @return original return type: 'double'
     */
    nextExponential?(): number;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints?(var0: java_lang_Integer | number, var1: java_lang_Integer | number): java_util_stream_IntStream | null;
    /**
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints?(): java_util_stream_IntStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints?(var0: java_lang_Long | bigint | number): java_util_stream_IntStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'java.util.stream.IntStream'
     */
    ints?(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number, var2: java_lang_Integer | number): java_util_stream_IntStream | null;
    /**
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles?(): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles?(var0: java_lang_Long | bigint | number, var1: java_lang_Double | number, var2: java_lang_Double | number): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles?(var0: java_lang_Double | number, var1: java_lang_Double | number): java_util_stream_DoubleStream | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.util.stream.DoubleStream'
     */
    doubles?(var0: java_lang_Long | bigint | number): java_util_stream_DoubleStream | null;
    /**
     * @return original return type: 'boolean'
     */
    nextBoolean?(): boolean;
}
/**
 * Create a proxy for the {@link RandomGenerator} interface.
 * All required methods in {@link RandomGeneratorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createRandomGeneratorProxy(methods: RandomGeneratorInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<RandomGeneratorInterface>;
declare const RandomGenerator_base: typeof RandomGeneratorClass;
/**
 * Class java.util.random.RandomGenerator.
 *
 * This actually imports the java class for further use.
 * The class {@link RandomGeneratorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RandomGenerator extends RandomGenerator_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default RandomGenerator;
