"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LutParameters = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.weasis.opencv.op.lut.LutParameters.
 *
 * This actually imports the java class for further use.
 * The class {@link LutParametersClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class LutParameters extends (0, java_bridge_1.importClass)('org.weasis.opencv.op.lut.LutParameters') {
}
exports.LutParameters = LutParameters;
exports.default = LutParameters;
