import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { LookupTableCV as org_weasis_opencv_data_LookupTableCV } from "./../../data/LookupTableCV";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { LutShape$eFunction as org_weasis_opencv_op_lut_LutShape$eFunction } from "./LutShape$eFunction";
/**
 * This class just defines types, you should import {@link LutShape} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LutShapeClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getLookup(): Promise<org_weasis_opencv_data_LookupTableCV | null>;
    /**
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getLookupSync(): org_weasis_opencv_data_LookupTableCV | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     */
    getFunctionType(): Promise<org_weasis_opencv_op_lut_LutShape$eFunction | null>;
    /**
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     */
    getFunctionTypeSync(): org_weasis_opencv_op_lut_LutShape$eFunction | null;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static getLutShape(var0: string | null): Promise<LutShape | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static getLutShapeSync(var0: string | null): LutShape | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * Original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static readonly LOG: LutShapeClass | null;
    /**
     * Original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static readonly LOG_INV: LutShapeClass | null;
    /**
     * Original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static readonly LINEAR: LutShapeClass | null;
    /**
     * Original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static readonly SIGMOID: LutShapeClass | null;
    /**
     * Original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static readonly SIGMOID_NORM: LutShapeClass | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     * @param var1 original type: 'java.lang.String'
     */
    constructor(var0: org_weasis_opencv_op_lut_LutShape$eFunction | null, var1: string | null);
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static newInstanceAsync(var0: org_weasis_opencv_op_lut_LutShape$eFunction | null, var1: string | null): Promise<LutShape>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     */
    constructor(var0: org_weasis_opencv_op_lut_LutShape$eFunction | null);
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.LutShape$eFunction'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static newInstanceAsync(var0: org_weasis_opencv_op_lut_LutShape$eFunction | null): Promise<LutShape>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var1 original type: 'java.lang.String'
     */
    constructor(var0: org_weasis_opencv_data_LookupTableCV | null, var1: string | null);
    /**
     * @param var0 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    static newInstanceAsync(var0: org_weasis_opencv_data_LookupTableCV | null, var1: string | null): Promise<LutShape>;
}
declare const LutShape_base: typeof LutShapeClass;
/**
 * Class org.weasis.opencv.op.lut.LutShape.
 *
 * This actually imports the java class for further use.
 * The class {@link LutShapeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LutShape extends LutShape_base {
}
export default LutShape;
