"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonParser = void 0;
exports.createJsonParserProxy = createJsonParserProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link JsonParser} interface.
 * All required methods in {@link JsonParserInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createJsonParserProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('jakarta.json.stream.JsonParser', methods, opts);
}
/**
 * Class jakarta.json.stream.JsonParser.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonParserClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonParser extends (0, java_bridge_1.importClass)('jakarta.json.stream.JsonParser') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.JsonParser = JsonParser;
exports.default = JsonParser;
