import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../lang/Class";
import { Long as java_lang_Long } from "./../../lang/Long";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Rectangle2D as java_awt_geom_Rectangle2D } from "./Rectangle2D";
import { Double as java_lang_Double } from "./../../lang/Double";
import { Rectangle as java_awt_Rectangle } from "./../Rectangle";
import { AffineTransform as java_awt_geom_AffineTransform } from "./AffineTransform";
import { Point2D as java_awt_geom_Point2D } from "./Point2D";
import { PathIterator as java_awt_geom_PathIterator } from "./PathIterator";
import { Shape as java_awt_Shape, ShapeInterface as java_awt_ShapeInterface } from "./../Shape";
/**
 * This class just defines types, you should import {@link Area} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class AreaClass extends JavaClass {
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    add(var0: AreaClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    addSync(var0: AreaClass | null): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    intersect(var0: AreaClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    intersectSync(var0: AreaClass | null): void;
    /**
     * @param var0 original type: 'java.awt.geom.Rectangle2D'
     * @return original return type: 'boolean'
     */
    intersects(var0: java_awt_geom_Rectangle2D | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.awt.geom.Rectangle2D'
     * @return original return type: 'boolean'
     */
    intersectsSync(var0: java_awt_geom_Rectangle2D | null): boolean;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @param var3 original type: 'double'
     * @return original return type: 'boolean'
     */
    intersects(var0: java_lang_Double | number, var1: java_lang_Double | number, var2: java_lang_Double | number, var3: java_lang_Double | number): Promise<boolean>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @param var3 original type: 'double'
     * @return original return type: 'boolean'
     */
    intersectsSync(var0: java_lang_Double | number, var1: java_lang_Double | number, var2: java_lang_Double | number, var3: java_lang_Double | number): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isSingular(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isSingularSync(): boolean;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    subtract(var0: AreaClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    subtractSync(var0: AreaClass | null): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'boolean'
     */
    isEmpty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEmptySync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isRectangular(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isRectangularSync(): boolean;
    /**
     * @return original return type: 'java.awt.Rectangle'
     */
    getBounds(): Promise<java_awt_Rectangle | null>;
    /**
     * @return original return type: 'java.awt.Rectangle'
     */
    getBoundsSync(): java_awt_Rectangle | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'boolean'
     */
    isPolygonal(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isPolygonalSync(): boolean;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'java.awt.geom.Area'
     */
    createTransformedArea(var0: java_awt_geom_AffineTransform | null): Promise<Area | null>;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'java.awt.geom.Area'
     */
    createTransformedAreaSync(var0: java_awt_geom_AffineTransform | null): Area | null;
    /**
     * @param var0 original type: 'java.awt.geom.Point2D'
     * @return original return type: 'boolean'
     */
    contains(var0: java_awt_geom_Point2D | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.awt.geom.Point2D'
     * @return original return type: 'boolean'
     */
    containsSync(var0: java_awt_geom_Point2D | null): boolean;
    /**
     * @param var0 original type: 'java.awt.geom.Rectangle2D'
     * @return original return type: 'boolean'
     */
    contains(var0: java_awt_geom_Rectangle2D | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.awt.geom.Rectangle2D'
     * @return original return type: 'boolean'
     */
    containsSync(var0: java_awt_geom_Rectangle2D | null): boolean;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'boolean'
     */
    contains(var0: java_lang_Double | number, var1: java_lang_Double | number): Promise<boolean>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @return original return type: 'boolean'
     */
    containsSync(var0: java_lang_Double | number, var1: java_lang_Double | number): boolean;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @param var3 original type: 'double'
     * @return original return type: 'boolean'
     */
    contains(var0: java_lang_Double | number, var1: java_lang_Double | number, var2: java_lang_Double | number, var3: java_lang_Double | number): Promise<boolean>;
    /**
     * @param var0 original type: 'double'
     * @param var1 original type: 'double'
     * @param var2 original type: 'double'
     * @param var3 original type: 'double'
     * @return original return type: 'boolean'
     */
    containsSync(var0: java_lang_Double | number, var1: java_lang_Double | number, var2: java_lang_Double | number, var3: java_lang_Double | number): boolean;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'void'
     */
    transform(var0: java_awt_geom_AffineTransform | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'void'
     */
    transformSync(var0: java_awt_geom_AffineTransform | null): void;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    exclusiveOr(var0: AreaClass | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'void'
     */
    exclusiveOrSync(var0: AreaClass | null): void;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'java.awt.geom.PathIterator'
     */
    getPathIterator(var0: java_awt_geom_AffineTransform | null): Promise<java_awt_geom_PathIterator | null>;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @return original return type: 'java.awt.geom.PathIterator'
     */
    getPathIteratorSync(var0: java_awt_geom_AffineTransform | null): java_awt_geom_PathIterator | null;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @param var1 original type: 'double'
     * @return original return type: 'java.awt.geom.PathIterator'
     */
    getPathIterator(var0: java_awt_geom_AffineTransform | null, var1: java_lang_Double | number): Promise<java_awt_geom_PathIterator | null>;
    /**
     * @param var0 original type: 'java.awt.geom.AffineTransform'
     * @param var1 original type: 'double'
     * @return original return type: 'java.awt.geom.PathIterator'
     */
    getPathIteratorSync(var0: java_awt_geom_AffineTransform | null, var1: java_lang_Double | number): java_awt_geom_PathIterator | null;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'boolean'
     */
    equals(var0: AreaClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.awt.geom.Area'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: AreaClass | null): boolean;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.Object'
     */
    clone(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    cloneSync(): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.awt.geom.Rectangle2D'
     */
    getBounds2D(): Promise<java_awt_geom_Rectangle2D | null>;
    /**
     * @return original return type: 'java.awt.geom.Rectangle2D'
     */
    getBounds2DSync(): java_awt_geom_Rectangle2D | null;
    /**
     * @return original return type: 'void'
     */
    reset(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    resetSync(): void;
    constructor();
    /**
     * @return original return type: 'java.awt.geom.Area'
     */
    static newInstanceAsync(): Promise<Area>;
    /**
     * @param var0 original type: 'java.awt.Shape'
     */
    constructor(var0: java_awt_Shape | JavaInterfaceProxy<java_awt_ShapeInterface> | null);
    /**
     * @param var0 original type: 'java.awt.Shape'
     * @return original return type: 'java.awt.geom.Area'
     */
    static newInstanceAsync(var0: java_awt_Shape | JavaInterfaceProxy<java_awt_ShapeInterface> | null): Promise<Area>;
}
declare const Area_base: typeof AreaClass;
/**
 * Class java.awt.geom.Area.
 *
 * This actually imports the java class for further use.
 * The class {@link AreaClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Area extends Area_base {
}
export default Area;
//# sourceMappingURL=Area.d.ts.map