import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { List as java_util_List } from "./../../../../java/util/List";
import { DicomImageAdapter as org_dcm4che3_img_DicomImageAdapter } from "./../DicomImageAdapter";
import { WlPresentation as org_weasis_opencv_op_lut_WlPresentation, WlPresentationInterface as org_weasis_opencv_op_lut_WlPresentationInterface } from "./../../../weasis/opencv/op/lut/WlPresentation";
import { LutShape as org_weasis_opencv_op_lut_LutShape } from "./../../../weasis/opencv/op/lut/LutShape";
import { LookupTableCV as org_weasis_opencv_data_LookupTableCV } from "./../../../weasis/opencv/data/LookupTableCV";
import { XMLStreamReader as javax_xml_stream_XMLStreamReader, XMLStreamReaderInterface as javax_xml_stream_XMLStreamReaderInterface } from "./../../../../javax/xml/stream/XMLStreamReader";
import { Map as java_util_Map } from "./../../../../java/util/Map";
import { Double as java_lang_Double } from "./../../../../java/lang/Double";
/**
 * This class just defines types, you should import {@link PresetWindowLevel} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PresetWindowLevelClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNameSync(): string | null;
    /**
     * @return original return type: 'double'
     */
    getWindow(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getWindowSync(): number;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.util.List'
     */
    static getPresetCollection(var0: org_dcm4che3_img_DicomImageAdapter | null, var1: string | null, var2: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.util.List'
     */
    static getPresetCollectionSync(var0: org_dcm4che3_img_DicomImageAdapter | null, var1: string | null, var2: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): java_util_List | null;
    /**
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    getLutShape(): Promise<org_weasis_opencv_op_lut_LutShape | null>;
    /**
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    getLutShapeSync(): org_weasis_opencv_op_lut_LutShape | null;
    /**
     * @param var0 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var1 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var2 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.dcm4che3.img.lut.PresetWindowLevel'
     */
    static buildPresetFromLutData(var0: org_dcm4che3_img_DicomImageAdapter | null, var1: org_weasis_opencv_data_LookupTableCV | null, var2: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var3: string | null): Promise<PresetWindowLevel | null>;
    /**
     * @param var0 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var1 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var2 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.dcm4che3.img.lut.PresetWindowLevel'
     */
    static buildPresetFromLutDataSync(var0: org_dcm4che3_img_DicomImageAdapter | null, var1: org_weasis_opencv_data_LookupTableCV | null, var2: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var3: string | null): PresetWindowLevel | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'double'
     */
    getLevel(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getLevelSync(): number;
    /**
     * @param var0 original type: 'javax.xml.stream.XMLStreamReader'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Integer'
     * @return original return type: 'java.lang.Integer'
     */
    static getIntegerTagAttribute(var0: javax_xml_stream_XMLStreamReader | JavaInterfaceProxy<javax_xml_stream_XMLStreamReaderInterface> | null, var1: string | null, var2: java_lang_Integer | number | null): Promise<number | null>;
    /**
     * @param var0 original type: 'javax.xml.stream.XMLStreamReader'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Integer'
     * @return original return type: 'java.lang.Integer'
     */
    static getIntegerTagAttributeSync(var0: javax_xml_stream_XMLStreamReader | JavaInterfaceProxy<javax_xml_stream_XMLStreamReaderInterface> | null, var1: string | null, var2: java_lang_Integer | number | null): number | null;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setKeyCode(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setKeyCodeSync(var0: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'double'
     */
    getMaxBox(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getMaxBoxSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    isAutoLevel(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAutoLevelSync(): boolean;
    /**
     * @return original return type: 'int'
     */
    getKeyCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getKeyCodeSync(): number;
    /**
     * @return original return type: 'java.util.Map'
     */
    static getPresetListByModality(): Promise<java_util_Map | null>;
    /**
     * @return original return type: 'java.util.Map'
     */
    static getPresetListByModalitySync(): java_util_Map | null;
    /**
     * @return original return type: 'double'
     */
    getMinBox(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    getMinBoxSync(): number;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Double'
     * @param var2 original type: 'java.lang.Double'
     * @param var3 original type: 'org.weasis.opencv.op.lut.LutShape'
     */
    constructor(var0: string | null, var1: java_lang_Double | number | null, var2: java_lang_Double | number | null, var3: org_weasis_opencv_op_lut_LutShape | null);
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Double'
     * @param var2 original type: 'java.lang.Double'
     * @param var3 original type: 'org.weasis.opencv.op.lut.LutShape'
     * @return original return type: 'org.dcm4che3.img.lut.PresetWindowLevel'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Double | number | null, var2: java_lang_Double | number | null, var3: org_weasis_opencv_op_lut_LutShape | null): Promise<PresetWindowLevel>;
}
declare const PresetWindowLevel_base: typeof PresetWindowLevelClass;
/**
 * Class org.dcm4che3.img.lut.PresetWindowLevel.
 *
 * This actually imports the java class for further use.
 * The class {@link PresetWindowLevelClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PresetWindowLevel extends PresetWindowLevel_base {
}
export default PresetWindowLevel;
//# sourceMappingURL=PresetWindowLevel.d.ts.map