import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../java/util/List";
import { Class as java_lang_Class } from "./../../java/lang/Class";
import { IIOMetadata as javax_imageio_metadata_IIOMetadata } from "./metadata/IIOMetadata";
import { Long as java_lang_Long } from "./../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../java/lang/Integer";
import { RenderedImage as java_awt_image_RenderedImage, RenderedImageInterface as java_awt_image_RenderedImageInterface } from "./../../java/awt/image/RenderedImage";
import { BufferedImage as java_awt_image_BufferedImage } from "./../../java/awt/image/BufferedImage";
import { Raster as java_awt_image_Raster } from "./../../java/awt/image/Raster";
/**
 * This class just defines types, you should import {@link IIOImage} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOImageClass extends JavaClass {
    /**
     * @return original return type: 'java.util.List'
     */
    getThumbnails(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getThumbnailsSync(): java_util_List | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadata'
     */
    getMetadata(): Promise<javax_imageio_metadata_IIOMetadata | null>;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadata'
     */
    getMetadataSync(): javax_imageio_metadata_IIOMetadata | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    setThumbnails(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    setThumbnailsSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @return original return type: 'java.awt.image.RenderedImage'
     */
    getRenderedImage(): Promise<java_awt_image_RenderedImage | null>;
    /**
     * @return original return type: 'java.awt.image.RenderedImage'
     */
    getRenderedImageSync(): java_awt_image_RenderedImage | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.awt.image.BufferedImage'
     */
    getThumbnail(var0: java_lang_Integer | number): Promise<java_awt_image_BufferedImage | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.awt.image.BufferedImage'
     */
    getThumbnailSync(var0: java_lang_Integer | number): java_awt_image_BufferedImage | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'boolean'
     */
    hasRaster(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasRasterSync(): boolean;
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'void'
     */
    setMetadata(var0: javax_imageio_metadata_IIOMetadata | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'void'
     */
    setMetadataSync(var0: javax_imageio_metadata_IIOMetadata | null): void;
    /**
     * @param var0 original type: 'java.awt.image.RenderedImage'
     * @return original return type: 'void'
     */
    setRenderedImage(var0: java_awt_image_RenderedImage | JavaInterfaceProxy<java_awt_image_RenderedImageInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.image.RenderedImage'
     * @return original return type: 'void'
     */
    setRenderedImageSync(var0: java_awt_image_RenderedImage | JavaInterfaceProxy<java_awt_image_RenderedImageInterface> | null): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    getNumThumbnails(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getNumThumbnailsSync(): number;
    /**
     * @param var0 original type: 'java.awt.image.Raster'
     * @return original return type: 'void'
     */
    setRaster(var0: java_awt_image_Raster | null): Promise<void>;
    /**
     * @param var0 original type: 'java.awt.image.Raster'
     * @return original return type: 'void'
     */
    setRasterSync(var0: java_awt_image_Raster | null): void;
    /**
     * @return original return type: 'java.awt.image.Raster'
     */
    getRaster(): Promise<java_awt_image_Raster | null>;
    /**
     * @return original return type: 'java.awt.image.Raster'
     */
    getRasterSync(): java_awt_image_Raster | null;
    /**
     * @param var0 original type: 'java.awt.image.RenderedImage'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'javax.imageio.metadata.IIOMetadata'
     */
    constructor(var0: java_awt_image_RenderedImage | JavaInterfaceProxy<java_awt_image_RenderedImageInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: javax_imageio_metadata_IIOMetadata | null);
    /**
     * @param var0 original type: 'java.awt.image.RenderedImage'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'javax.imageio.IIOImage'
     */
    static newInstanceAsync(var0: java_awt_image_RenderedImage | JavaInterfaceProxy<java_awt_image_RenderedImageInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: javax_imageio_metadata_IIOMetadata | null): Promise<IIOImage>;
    /**
     * @param var0 original type: 'java.awt.image.Raster'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'javax.imageio.metadata.IIOMetadata'
     */
    constructor(var0: java_awt_image_Raster | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: javax_imageio_metadata_IIOMetadata | null);
    /**
     * @param var0 original type: 'java.awt.image.Raster'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'javax.imageio.IIOImage'
     */
    static newInstanceAsync(var0: java_awt_image_Raster | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: javax_imageio_metadata_IIOMetadata | null): Promise<IIOImage>;
}
declare const IIOImage_base: typeof IIOImageClass;
/**
 * Class javax.imageio.IIOImage.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOImageClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOImage extends IIOImage_base {
}
export default IIOImage;
