"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIOParamController = void 0;
exports.createIIOParamControllerProxy = createIIOParamControllerProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IIOParamController} interface.
 * All required methods in {@link IIOParamControllerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIIOParamControllerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.imageio.IIOParamController', methods, opts);
}
/**
 * Class javax.imageio.IIOParamController.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOParamControllerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IIOParamController extends (0, java_bridge_1.importClass)('javax.imageio.IIOParamController') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IIOParamController = IIOParamController;
exports.default = IIOParamController;
