"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIOReadProgressListener = void 0;
exports.createIIOReadProgressListenerProxy = createIIOReadProgressListenerProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IIOReadProgressListener} interface.
 * All required methods in {@link IIOReadProgressListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIIOReadProgressListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.imageio.event.IIOReadProgressListener', methods, opts);
}
/**
 * Class javax.imageio.event.IIOReadProgressListener.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOReadProgressListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IIOReadProgressListener extends (0, java_bridge_1.importClass)('javax.imageio.event.IIOReadProgressListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IIOReadProgressListener = IIOReadProgressListener;
exports.default = IIOReadProgressListener;
