import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Set as java_util_Set } from "./../../util/Set";
import { Class as java_lang_Class } from "./../Class";
import { Integer as java_lang_Integer } from "./../Integer";
/**
 * This class just defines types, you should import {@link Member} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MemberClass extends JavaClass {
    /**
     * @return original return type: 'java.util.Set'
     */
    accessFlags(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    accessFlagsSync(): java_util_Set | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNameSync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isSynthetic(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isSyntheticSync(): boolean;
    /**
     * @return original return type: 'int'
     */
    getModifiers(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getModifiersSync(): number;
    /**
     * Original type: 'int'
     */
    static readonly PUBLIC: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly DECLARED: java_lang_Integer | number;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createMemberProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface MemberInterface {
    /**
     * @return original return type: 'java.util.Set'
     */
    accessFlags?(): java_util_Set | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): java_lang_Class | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getName(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isSynthetic(): boolean;
    /**
     * @return original return type: 'int'
     */
    getModifiers(): number;
}
/**
 * Create a proxy for the {@link Member} interface.
 * All required methods in {@link MemberInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createMemberProxy(methods: MemberInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<MemberInterface>;
declare const Member_base: typeof MemberClass;
/**
 * Class java.lang.reflect.Member.
 *
 * This actually imports the java class for further use.
 * The class {@link MemberClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Member extends Member_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default Member;
