"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIOMetadataFormat = void 0;
exports.createIIOMetadataFormatProxy = createIIOMetadataFormatProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IIOMetadataFormat} interface.
 * All required methods in {@link IIOMetadataFormatInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIIOMetadataFormatProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.imageio.metadata.IIOMetadataFormat', methods, opts);
}
/**
 * Class javax.imageio.metadata.IIOMetadataFormat.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOMetadataFormatClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IIOMetadataFormat extends (0, java_bridge_1.importClass)('javax.imageio.metadata.IIOMetadataFormat') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IIOMetadataFormat = IIOMetadataFormat;
exports.default = IIOMetadataFormat;
