import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IIOMetadata as javax_imageio_metadata_IIOMetadata } from "./IIOMetadata";
/**
 * This class just defines types, you should import {@link IIOMetadataController} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOMetadataControllerClass extends JavaClass {
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'boolean'
     */
    activate(var0: javax_imageio_metadata_IIOMetadata | null): Promise<boolean>;
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'boolean'
     */
    activateSync(var0: javax_imageio_metadata_IIOMetadata | null): boolean;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIIOMetadataControllerProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IIOMetadataControllerInterface {
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadata'
     * @return original return type: 'boolean'
     */
    activate(var0: javax_imageio_metadata_IIOMetadata | null): boolean;
}
/**
 * Create a proxy for the {@link IIOMetadataController} interface.
 * All required methods in {@link IIOMetadataControllerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIIOMetadataControllerProxy(methods: IIOMetadataControllerInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IIOMetadataControllerInterface>;
declare const IIOMetadataController_base: typeof IIOMetadataControllerClass;
/**
 * Class javax.imageio.metadata.IIOMetadataController.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOMetadataControllerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOMetadataController extends IIOMetadataController_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IIOMetadataController;
//# sourceMappingURL=IIOMetadataController.d.ts.map