import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Node as org_w3c_dom_Node, NodeInterface as org_w3c_dom_NodeInterface } from "./../../../org/w3c/dom/Node";
import { IIOMetadataController as javax_imageio_metadata_IIOMetadataController, IIOMetadataControllerInterface as javax_imageio_metadata_IIOMetadataControllerInterface } from "./IIOMetadataController";
import { IIOMetadataFormat as javax_imageio_metadata_IIOMetadataFormat } from "./IIOMetadataFormat";
/**
 * This class just defines types, you should import {@link IIOMetadata} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOMetadataClass extends JavaClass {
    /**
     * @return original return type: 'boolean'
     */
    hasController(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasControllerSync(): boolean;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @return original return type: 'java.lang.String[]'
     */
    getExtraMetadataFormatNames(): Promise<(string | null)[] | null>;
    /**
     * @return original return type: 'java.lang.String[]'
     */
    getExtraMetadataFormatNamesSync(): (string | null)[] | null;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.w3c.dom.Node'
     * @return original return type: 'void'
     */
    setFromTree(var0: string | null, var1: org_w3c_dom_Node | JavaInterfaceProxy<org_w3c_dom_NodeInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.w3c.dom.Node'
     * @return original return type: 'void'
     */
    setFromTreeSync(var0: string | null, var1: org_w3c_dom_Node | JavaInterfaceProxy<org_w3c_dom_NodeInterface> | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNativeMetadataFormatName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNativeMetadataFormatNameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.w3c.dom.Node'
     * @return original return type: 'void'
     */
    mergeTree(var0: string | null, var1: org_w3c_dom_Node | JavaInterfaceProxy<org_w3c_dom_NodeInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.w3c.dom.Node'
     * @return original return type: 'void'
     */
    mergeTreeSync(var0: string | null, var1: org_w3c_dom_Node | JavaInterfaceProxy<org_w3c_dom_NodeInterface> | null): void;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadataController'
     */
    getController(): Promise<javax_imageio_metadata_IIOMetadataController | null>;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadataController'
     */
    getControllerSync(): javax_imageio_metadata_IIOMetadataController | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'boolean'
     */
    isStandardMetadataFormatSupported(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isStandardMetadataFormatSupportedSync(): boolean;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadataController'
     */
    getDefaultController(): Promise<javax_imageio_metadata_IIOMetadataController | null>;
    /**
     * @return original return type: 'javax.imageio.metadata.IIOMetadataController'
     */
    getDefaultControllerSync(): javax_imageio_metadata_IIOMetadataController | null;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnly(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnlySync(): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    activateController(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    activateControllerSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'void'
     */
    reset(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    resetSync(): void;
    /**
     * @return original return type: 'java.lang.String[]'
     */
    getMetadataFormatNames(): Promise<(string | null)[] | null>;
    /**
     * @return original return type: 'java.lang.String[]'
     */
    getMetadataFormatNamesSync(): (string | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'javax.imageio.metadata.IIOMetadataFormat'
     */
    getMetadataFormat(var0: string | null): Promise<javax_imageio_metadata_IIOMetadataFormat | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'javax.imageio.metadata.IIOMetadataFormat'
     */
    getMetadataFormatSync(var0: string | null): javax_imageio_metadata_IIOMetadataFormat | null;
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadataController'
     * @return original return type: 'void'
     */
    setController(var0: javax_imageio_metadata_IIOMetadataController | JavaInterfaceProxy<javax_imageio_metadata_IIOMetadataControllerInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'javax.imageio.metadata.IIOMetadataController'
     * @return original return type: 'void'
     */
    setControllerSync(var0: javax_imageio_metadata_IIOMetadataController | JavaInterfaceProxy<javax_imageio_metadata_IIOMetadataControllerInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.w3c.dom.Node'
     */
    getAsTree(var0: string | null): Promise<org_w3c_dom_Node | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.w3c.dom.Node'
     */
    getAsTreeSync(var0: string | null): org_w3c_dom_Node | null;
}
declare const IIOMetadata_base: typeof IIOMetadataClass;
/**
 * Class javax.imageio.metadata.IIOMetadata.
 *
 * This actually imports the java class for further use.
 * The class {@link IIOMetadataClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IIOMetadata extends IIOMetadata_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IIOMetadata;
