"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyListener = void 0;
exports.createKeyListenerProxy = createKeyListenerProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link KeyListener} interface.
 * All required methods in {@link KeyListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createKeyListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.event.KeyListener', methods, opts);
}
/**
 * Class java.awt.event.KeyListener.
 *
 * This actually imports the java class for further use.
 * The class {@link KeyListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class KeyListener extends (0, java_bridge_1.importClass)('java.awt.event.KeyListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.KeyListener = KeyListener;
exports.default = KeyListener;
