"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowFocusListener = void 0;
exports.createWindowFocusListenerProxy = createWindowFocusListenerProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link WindowFocusListener} interface.
 * All required methods in {@link WindowFocusListenerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createWindowFocusListenerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.awt.event.WindowFocusListener', methods, opts);
}
/**
 * Class java.awt.event.WindowFocusListener.
 *
 * This actually imports the java class for further use.
 * The class {@link WindowFocusListenerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class WindowFocusListener extends (0, java_bridge_1.importClass)('java.awt.event.WindowFocusListener') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.WindowFocusListener = WindowFocusListener;
exports.default = WindowFocusListener;
