"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Level = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.slf4j.event.Level.
 *
 * This actually imports the java class for further use.
 * The class {@link LevelClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Level extends (0, java_bridge_1.importClass)('org.slf4j.event.Level') {
}
exports.Level = Level;
exports.default = Level;
