"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnatomicBuilder$CategoryBuilder = void 0;
exports.createAnatomicBuilder$CategoryBuilderProxy = createAnatomicBuilder$CategoryBuilderProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AnatomicBuilder$CategoryBuilder} interface.
 * All required methods in {@link AnatomicBuilder$CategoryBuilderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAnatomicBuilder$CategoryBuilderProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.weasis.dicom.ref.AnatomicBuilder$CategoryBuilder', methods, opts);
}
/**
 * Class org.weasis.dicom.ref.AnatomicBuilder$CategoryBuilder.
 *
 * This actually imports the java class for further use.
 * The class {@link AnatomicBuilder$CategoryBuilderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AnatomicBuilder$CategoryBuilder extends (0, java_bridge_1.importClass)('org.weasis.dicom.ref.AnatomicBuilder$CategoryBuilder') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AnatomicBuilder$CategoryBuilder = AnatomicBuilder$CategoryBuilder;
exports.default = AnatomicBuilder$CategoryBuilder;
