"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnatomicRegion = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.weasis.dicom.ref.AnatomicRegion.
 *
 * This actually imports the java class for further use.
 * The class {@link AnatomicRegionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AnatomicRegion extends (0, java_bridge_1.importClass)('org.weasis.dicom.ref.AnatomicRegion') {
}
exports.AnatomicRegion = AnatomicRegion;
exports.default = AnatomicRegion;
