"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnatomicItem = void 0;
exports.createAnatomicItemProxy = createAnatomicItemProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AnatomicItem} interface.
 * All required methods in {@link AnatomicItemInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAnatomicItemProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.weasis.dicom.ref.AnatomicItem', methods, opts);
}
/**
 * Class org.weasis.dicom.ref.AnatomicItem.
 *
 * This actually imports the java class for further use.
 * The class {@link AnatomicItemClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AnatomicItem extends (0, java_bridge_1.importClass)('org.weasis.dicom.ref.AnatomicItem') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AnatomicItem = AnatomicItem;
exports.default = AnatomicItem;
