"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnatomicModifier = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.weasis.dicom.ref.AnatomicModifier.
 *
 * This actually imports the java class for further use.
 * The class {@link AnatomicModifierClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AnatomicModifier extends (0, java_bridge_1.importClass)('org.weasis.dicom.ref.AnatomicModifier') {
}
exports.AnatomicModifier = AnatomicModifier;
exports.default = AnatomicModifier;
