import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Integer as java_lang_Integer } from "./../../lang/Integer";
import { Class as java_lang_Class } from "./../../lang/Class";
import { Long as java_lang_Long } from "./../../lang/Long";
/**
 * This class just defines types, you should import {@link CoderResult} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class CoderResultClass extends JavaClass {
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.charset.CoderResult'
     */
    static malformedForLength(var0: java_lang_Integer | number): Promise<CoderResult | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.charset.CoderResult'
     */
    static malformedForLengthSync(var0: java_lang_Integer | number): CoderResult | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'boolean'
     */
    isMalformed(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isMalformedSync(): boolean;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'boolean'
     */
    isOverflow(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isOverflowSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isUnmappable(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isUnmappableSync(): boolean;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'int'
     */
    length(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    lengthSync(): number;
    /**
     * @return original return type: 'void'
     */
    throwException(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    throwExceptionSync(): void;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.charset.CoderResult'
     */
    static unmappableForLength(var0: java_lang_Integer | number): Promise<CoderResult | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.nio.charset.CoderResult'
     */
    static unmappableForLengthSync(var0: java_lang_Integer | number): CoderResult | null;
    /**
     * @return original return type: 'boolean'
     */
    isError(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isErrorSync(): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isUnderflow(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isUnderflowSync(): boolean;
    /**
     * Original type: 'java.nio.charset.CoderResult'
     */
    static readonly OVERFLOW: CoderResultClass | null;
    /**
     * Original type: 'java.nio.charset.CoderResult'
     */
    static readonly UNDERFLOW: CoderResultClass | null;
}
declare const CoderResult_base: typeof CoderResultClass;
/**
 * Class java.nio.charset.CoderResult.
 *
 * This actually imports the java class for further use.
 * The class {@link CoderResultClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class CoderResult extends CoderResult_base {
}
export default CoderResult;
