"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonPointer = void 0;
exports.createJsonPointerProxy = createJsonPointerProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link JsonPointer} interface.
 * All required methods in {@link JsonPointerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createJsonPointerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('jakarta.json.JsonPointer', methods, opts);
}
/**
 * Class jakarta.json.JsonPointer.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonPointerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonPointer extends (0, java_bridge_1.importClass)('jakarta.json.JsonPointer') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.JsonPointer = JsonPointer;
exports.default = JsonPointer;
