import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonObject as jakarta_json_JsonObject, JsonObjectInterface as jakarta_json_JsonObjectInterface } from "./JsonObject";
import { JsonArray as jakarta_json_JsonArray, JsonArrayInterface as jakarta_json_JsonArrayInterface } from "./JsonArray";
import { JsonValue as jakarta_json_JsonValue, JsonValueInterface as jakarta_json_JsonValueInterface } from "./JsonValue";
import { BigDecimal as java_math_BigDecimal } from "./../../java/math/BigDecimal";
import { BigInteger as java_math_BigInteger } from "./../../java/math/BigInteger";
import { Number as java_lang_Number } from "./../../java/lang/Number";
import { JsonValue$ValueType as jakarta_json_JsonValue$ValueType } from "./JsonValue$ValueType";
/**
 * This class just defines types, you should import {@link JsonNumber} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonNumberClass extends JavaClass {
    /**
     * Original type: 'jakarta.json.JsonObject'
     */
    static readonly EMPTY_JSON_OBJECT: jakarta_json_JsonObject | JavaInterfaceProxy<jakarta_json_JsonObjectInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonArray'
     */
    static readonly EMPTY_JSON_ARRAY: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly NULL: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly TRUE: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly FALSE: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
    /**
     * @return original return type: 'java.math.BigDecimal'
     */
    bigDecimalValue(): Promise<java_math_BigDecimal | null>;
    /**
     * @return original return type: 'java.math.BigDecimal'
     */
    bigDecimalValueSync(): java_math_BigDecimal | null;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValueExact(): Promise<java_math_BigInteger | null>;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValueExactSync(): java_math_BigInteger | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): string;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'int'
     */
    intValue(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    intValueSync(): number;
    /**
     * @return original return type: 'long'
     */
    longValue(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    longValueSync(): number;
    /**
     * @return original return type: 'double'
     */
    doubleValue(): Promise<number>;
    /**
     * @return original return type: 'double'
     */
    doubleValueSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    isIntegral(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isIntegralSync(): boolean;
    /**
     * @return original return type: 'java.lang.Number'
     */
    numberValue(): Promise<java_lang_Number | null>;
    /**
     * @return original return type: 'java.lang.Number'
     */
    numberValueSync(): java_lang_Number | null;
    /**
     * @return original return type: 'long'
     */
    longValueExact(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    longValueExactSync(): number;
    /**
     * @return original return type: 'int'
     */
    intValueExact(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    intValueExactSync(): number;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValue(): Promise<java_math_BigInteger | null>;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValueSync(): java_math_BigInteger | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray(): Promise<jakarta_json_JsonArray | null>;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArraySync(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject(): Promise<jakarta_json_JsonObject | null>;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObjectSync(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): Promise<jakarta_json_JsonValue$ValueType | null>;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueTypeSync(): jakarta_json_JsonValue$ValueType | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonNumberProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonNumberInterface {
    /**
     * @return original return type: 'java.math.BigDecimal'
     */
    bigDecimalValue(): java_math_BigDecimal | null;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValueExact(): java_math_BigInteger | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): number;
    /**
     * @return original return type: 'int'
     */
    intValue(): number;
    /**
     * @return original return type: 'long'
     */
    longValue(): number;
    /**
     * @return original return type: 'double'
     */
    doubleValue(): number;
    /**
     * @return original return type: 'boolean'
     */
    isIntegral(): boolean;
    /**
     * @return original return type: 'java.lang.Number'
     */
    numberValue?(): java_lang_Number | null;
    /**
     * @return original return type: 'long'
     */
    longValueExact(): number;
    /**
     * @return original return type: 'int'
     */
    intValueExact(): number;
    /**
     * @return original return type: 'java.math.BigInteger'
     */
    bigIntegerValue(): java_math_BigInteger | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray?(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject?(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): jakarta_json_JsonValue$ValueType | null;
}
/**
 * Create a proxy for the {@link JsonNumber} interface.
 * All required methods in {@link JsonNumberInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonNumberProxy(methods: JsonNumberInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonNumberInterface>;
declare const JsonNumber_base: typeof JsonNumberClass;
/**
 * Class jakarta.json.JsonNumber.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonNumberClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonNumber extends JsonNumber_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonNumber;
//# sourceMappingURL=JsonNumber.d.ts.map