import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonObject as jakarta_json_JsonObject, JsonObjectInterface as jakarta_json_JsonObjectInterface } from "./JsonObject";
import { JsonArray as jakarta_json_JsonArray, JsonArrayInterface as jakarta_json_JsonArrayInterface } from "./JsonArray";
import { JsonValue$ValueType as jakarta_json_JsonValue$ValueType } from "./JsonValue$ValueType";
/**
 * This class just defines types, you should import {@link JsonValue} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonValueClass extends JavaClass {
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject(): Promise<jakarta_json_JsonObject | null>;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObjectSync(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray(): Promise<jakarta_json_JsonArray | null>;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArraySync(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): Promise<jakarta_json_JsonValue$ValueType | null>;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueTypeSync(): jakarta_json_JsonValue$ValueType | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly NULL: JsonValueClass | JavaInterfaceProxy<JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonObject'
     */
    static readonly EMPTY_JSON_OBJECT: jakarta_json_JsonObject | JavaInterfaceProxy<jakarta_json_JsonObjectInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonArray'
     */
    static readonly EMPTY_JSON_ARRAY: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly TRUE: JsonValueClass | JavaInterfaceProxy<JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly FALSE: JsonValueClass | JavaInterfaceProxy<JsonValueInterface> | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonValueProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonValueInterface {
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject?(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray?(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): string;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): jakarta_json_JsonValue$ValueType | null;
}
/**
 * Create a proxy for the {@link JsonValue} interface.
 * All required methods in {@link JsonValueInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonValueProxy(methods: JsonValueInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonValueInterface>;
declare const JsonValue_base: typeof JsonValueClass;
/**
 * Class jakarta.json.JsonValue.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonValueClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonValue extends JsonValue_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonValue;
