import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../java/lang/Class";
import { Long as java_lang_Long } from "./../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../java/lang/Integer";
import { JsonBuilderFactory as jakarta_json_JsonBuilderFactory } from "./JsonBuilderFactory";
import { Map as java_util_Map, MapInterface as java_util_MapInterface } from "./../../java/util/Map";
import { JsonWriterFactory as jakarta_json_JsonWriterFactory } from "./JsonWriterFactory";
import { JsonReaderFactory as jakarta_json_JsonReaderFactory } from "./JsonReaderFactory";
import { JsonGeneratorFactory as jakarta_json_stream_JsonGeneratorFactory } from "./stream/JsonGeneratorFactory";
import { JsonPatch as jakarta_json_JsonPatch } from "./JsonPatch";
import { JsonArray as jakarta_json_JsonArray, JsonArrayInterface as jakarta_json_JsonArrayInterface } from "./JsonArray";
import { JsonNumber as jakarta_json_JsonNumber } from "./JsonNumber";
import { Double as java_lang_Double } from "./../../java/lang/Double";
import { BigDecimal as java_math_BigDecimal } from "./../../java/math/BigDecimal";
import { BigInteger as java_math_BigInteger } from "./../../java/math/BigInteger";
import { Number as java_lang_Number } from "./../../java/lang/Number";
import { JsonString as jakarta_json_JsonString } from "./JsonString";
import { JsonParser as jakarta_json_stream_JsonParser } from "./stream/JsonParser";
import { InputStream as java_io_InputStream } from "./../../java/io/InputStream";
import { Reader as java_io_Reader } from "./../../java/io/Reader";
import { JsonParserFactory as jakarta_json_stream_JsonParserFactory } from "./stream/JsonParserFactory";
import { JsonMergePatch as jakarta_json_JsonMergePatch } from "./JsonMergePatch";
import { JsonValue as jakarta_json_JsonValue, JsonValueInterface as jakarta_json_JsonValueInterface } from "./JsonValue";
import { JsonPatchBuilder as jakarta_json_JsonPatchBuilder } from "./JsonPatchBuilder";
import { JsonReader as jakarta_json_JsonReader } from "./JsonReader";
import { JsonPointer as jakarta_json_JsonPointer } from "./JsonPointer";
import { JsonObjectBuilder as jakarta_json_JsonObjectBuilder } from "./JsonObjectBuilder";
import { JsonObject as jakarta_json_JsonObject, JsonObjectInterface as jakarta_json_JsonObjectInterface } from "./JsonObject";
import { JsonGenerator as jakarta_json_stream_JsonGenerator } from "./stream/JsonGenerator";
import { Writer as java_io_Writer } from "./../../java/io/Writer";
import { OutputStream as java_io_OutputStream } from "./../../java/io/OutputStream";
import { JsonArrayBuilder as jakarta_json_JsonArrayBuilder } from "./JsonArrayBuilder";
import { Collection as java_util_Collection, CollectionInterface as java_util_CollectionInterface } from "./../../java/util/Collection";
import { JsonWriter as jakarta_json_JsonWriter } from "./JsonWriter";
import { JsonStructure as jakarta_json_JsonStructure, JsonStructureInterface as jakarta_json_JsonStructureInterface } from "./JsonStructure";
/**
 * This class just defines types, you should import {@link Json} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonBuilderFactory'
     */
    static createBuilderFactory(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_JsonBuilderFactory | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonBuilderFactory'
     */
    static createBuilderFactorySync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_JsonBuilderFactory | null;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonWriterFactory'
     */
    static createWriterFactory(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_JsonWriterFactory | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonWriterFactory'
     */
    static createWriterFactorySync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_JsonWriterFactory | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonReaderFactory'
     */
    static createReaderFactory(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_JsonReaderFactory | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonReaderFactory'
     */
    static createReaderFactorySync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_JsonReaderFactory | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.stream.JsonGeneratorFactory'
     */
    static createGeneratorFactory(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_stream_JsonGeneratorFactory | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.stream.JsonGeneratorFactory'
     */
    static createGeneratorFactorySync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_stream_JsonGeneratorFactory | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonPatch'
     */
    static createPatch(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): Promise<jakarta_json_JsonPatch | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonPatch'
     */
    static createPatchSync(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): jakarta_json_JsonPatch | null;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static decodePointer(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static decodePointerSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_lang_Long | bigint | number): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_lang_Long | bigint | number): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_lang_Double | number): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'double'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_lang_Double | number): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'java.math.BigDecimal'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_math_BigDecimal | null): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'java.math.BigDecimal'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_math_BigDecimal | null): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'java.math.BigInteger'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_math_BigInteger | null): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'java.math.BigInteger'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_math_BigInteger | null): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'java.lang.Number'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_lang_Number | null): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'java.lang.Number'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_lang_Number | null): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonString'
     */
    static createValue(var0: string | null): Promise<jakarta_json_JsonString | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonString'
     */
    static createValueSync(var0: string | null): jakarta_json_JsonString | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValue(var0: java_lang_Integer | number): Promise<jakarta_json_JsonNumber | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'jakarta.json.JsonNumber'
     */
    static createValueSync(var0: java_lang_Integer | number): jakarta_json_JsonNumber | null;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'jakarta.json.stream.JsonParser'
     */
    static createParser(var0: java_io_InputStream | null): Promise<jakarta_json_stream_JsonParser | null>;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'jakarta.json.stream.JsonParser'
     */
    static createParserSync(var0: java_io_InputStream | null): jakarta_json_stream_JsonParser | null;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'jakarta.json.stream.JsonParser'
     */
    static createParser(var0: java_io_Reader | null): Promise<jakarta_json_stream_JsonParser | null>;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'jakarta.json.stream.JsonParser'
     */
    static createParserSync(var0: java_io_Reader | null): jakarta_json_stream_JsonParser | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.stream.JsonParserFactory'
     */
    static createParserFactory(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_stream_JsonParserFactory | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.stream.JsonParserFactory'
     */
    static createParserFactorySync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_stream_JsonParserFactory | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonValue'
     * @param var1 original type: 'jakarta.json.JsonValue'
     * @return original return type: 'jakarta.json.JsonMergePatch'
     */
    static createMergeDiff(var0: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null, var1: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null): Promise<jakarta_json_JsonMergePatch | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonValue'
     * @param var1 original type: 'jakarta.json.JsonValue'
     * @return original return type: 'jakarta.json.JsonMergePatch'
     */
    static createMergeDiffSync(var0: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null, var1: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null): jakarta_json_JsonMergePatch | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonPatchBuilder'
     */
    static createPatchBuilder(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): Promise<jakarta_json_JsonPatchBuilder | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonPatchBuilder'
     */
    static createPatchBuilderSync(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): jakarta_json_JsonPatchBuilder | null;
    /**
     * @return original return type: 'jakarta.json.JsonPatchBuilder'
     */
    static createPatchBuilder(): Promise<jakarta_json_JsonPatchBuilder | null>;
    /**
     * @return original return type: 'jakarta.json.JsonPatchBuilder'
     */
    static createPatchBuilderSync(): jakarta_json_JsonPatchBuilder | null;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'jakarta.json.JsonReader'
     */
    static createReader(var0: java_io_Reader | null): Promise<jakarta_json_JsonReader | null>;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'jakarta.json.JsonReader'
     */
    static createReaderSync(var0: java_io_Reader | null): jakarta_json_JsonReader | null;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'jakarta.json.JsonReader'
     */
    static createReader(var0: java_io_InputStream | null): Promise<jakarta_json_JsonReader | null>;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'jakarta.json.JsonReader'
     */
    static createReaderSync(var0: java_io_InputStream | null): jakarta_json_JsonReader | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonValue'
     * @return original return type: 'jakarta.json.JsonMergePatch'
     */
    static createMergePatch(var0: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null): Promise<jakarta_json_JsonMergePatch | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonValue'
     * @return original return type: 'jakarta.json.JsonMergePatch'
     */
    static createMergePatchSync(var0: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null): jakarta_json_JsonMergePatch | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonPointer'
     */
    static createPointer(var0: string | null): Promise<jakarta_json_JsonPointer | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonPointer'
     */
    static createPointerSync(var0: string | null): jakarta_json_JsonPointer | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonObject'
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilder(var0: jakarta_json_JsonObject | JavaInterfaceProxy<jakarta_json_JsonObjectInterface> | null): Promise<jakarta_json_JsonObjectBuilder | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonObject'
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilderSync(var0: jakarta_json_JsonObject | JavaInterfaceProxy<jakarta_json_JsonObjectInterface> | null): jakarta_json_JsonObjectBuilder | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilder(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<jakarta_json_JsonObjectBuilder | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilderSync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): jakarta_json_JsonObjectBuilder | null;
    /**
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilder(): Promise<jakarta_json_JsonObjectBuilder | null>;
    /**
     * @return original return type: 'jakarta.json.JsonObjectBuilder'
     */
    static createObjectBuilderSync(): jakarta_json_JsonObjectBuilder | null;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @return original return type: 'jakarta.json.stream.JsonGenerator'
     */
    static createGenerator(var0: java_io_Writer | null): Promise<jakarta_json_stream_JsonGenerator | null>;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @return original return type: 'jakarta.json.stream.JsonGenerator'
     */
    static createGeneratorSync(var0: java_io_Writer | null): jakarta_json_stream_JsonGenerator | null;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @return original return type: 'jakarta.json.stream.JsonGenerator'
     */
    static createGenerator(var0: java_io_OutputStream | null): Promise<jakarta_json_stream_JsonGenerator | null>;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @return original return type: 'jakarta.json.stream.JsonGenerator'
     */
    static createGeneratorSync(var0: java_io_OutputStream | null): jakarta_json_stream_JsonGenerator | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilder(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<jakarta_json_JsonArrayBuilder | null>;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilderSync(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): jakarta_json_JsonArrayBuilder | null;
    /**
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilder(): Promise<jakarta_json_JsonArrayBuilder | null>;
    /**
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilderSync(): jakarta_json_JsonArrayBuilder | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilder(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): Promise<jakarta_json_JsonArrayBuilder | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonArray'
     * @return original return type: 'jakarta.json.JsonArrayBuilder'
     */
    static createArrayBuilderSync(var0: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null): jakarta_json_JsonArrayBuilder | null;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @return original return type: 'jakarta.json.JsonWriter'
     */
    static createWriter(var0: java_io_Writer | null): Promise<jakarta_json_JsonWriter | null>;
    /**
     * @param var0 original type: 'java.io.Writer'
     * @return original return type: 'jakarta.json.JsonWriter'
     */
    static createWriterSync(var0: java_io_Writer | null): jakarta_json_JsonWriter | null;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @return original return type: 'jakarta.json.JsonWriter'
     */
    static createWriter(var0: java_io_OutputStream | null): Promise<jakarta_json_JsonWriter | null>;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @return original return type: 'jakarta.json.JsonWriter'
     */
    static createWriterSync(var0: java_io_OutputStream | null): jakarta_json_JsonWriter | null;
    /**
     * @param var0 original type: 'jakarta.json.JsonStructure'
     * @param var1 original type: 'jakarta.json.JsonStructure'
     * @return original return type: 'jakarta.json.JsonPatch'
     */
    static createDiff(var0: jakarta_json_JsonStructure | JavaInterfaceProxy<jakarta_json_JsonStructureInterface> | null, var1: jakarta_json_JsonStructure | JavaInterfaceProxy<jakarta_json_JsonStructureInterface> | null): Promise<jakarta_json_JsonPatch | null>;
    /**
     * @param var0 original type: 'jakarta.json.JsonStructure'
     * @param var1 original type: 'jakarta.json.JsonStructure'
     * @return original return type: 'jakarta.json.JsonPatch'
     */
    static createDiffSync(var0: jakarta_json_JsonStructure | JavaInterfaceProxy<jakarta_json_JsonStructureInterface> | null, var1: jakarta_json_JsonStructure | JavaInterfaceProxy<jakarta_json_JsonStructureInterface> | null): jakarta_json_JsonPatch | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static encodePointer(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static encodePointerSync(var0: string | null): string | null;
}
declare const Json_base: typeof JsonClass;
/**
 * Class jakarta.json.Json.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Json extends Json_base {
}
export default Json;
