"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonStructure = void 0;
exports.createJsonStructureProxy = createJsonStructureProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link JsonStructure} interface.
 * All required methods in {@link JsonStructureInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createJsonStructureProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('jakarta.json.JsonStructure', methods, opts);
}
/**
 * Class jakarta.json.JsonStructure.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonStructureClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonStructure extends (0, java_bridge_1.importClass)('jakarta.json.JsonStructure') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.JsonStructure = JsonStructure;
exports.default = JsonStructure;
