import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonValue as jakarta_json_JsonValue, JsonValueInterface as jakarta_json_JsonValueInterface } from "./JsonValue";
import { JsonObject as jakarta_json_JsonObject, JsonObjectInterface as jakarta_json_JsonObjectInterface } from "./JsonObject";
import { JsonArray as jakarta_json_JsonArray, JsonArrayInterface as jakarta_json_JsonArrayInterface } from "./JsonArray";
import { JsonValue$ValueType as jakarta_json_JsonValue$ValueType } from "./JsonValue$ValueType";
/**
 * This class just defines types, you should import {@link JsonStructure} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonStructureClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonValue'
     */
    getValue(var0: string | null): Promise<jakarta_json_JsonValue | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonValue'
     */
    getValueSync(var0: string | null): jakarta_json_JsonValue | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject(): Promise<jakarta_json_JsonObject | null>;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObjectSync(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray(): Promise<jakarta_json_JsonArray | null>;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArraySync(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): Promise<jakarta_json_JsonValue$ValueType | null>;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueTypeSync(): jakarta_json_JsonValue$ValueType | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly NULL: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonObject'
     */
    static readonly EMPTY_JSON_OBJECT: jakarta_json_JsonObject | JavaInterfaceProxy<jakarta_json_JsonObjectInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonArray'
     */
    static readonly EMPTY_JSON_ARRAY: jakarta_json_JsonArray | JavaInterfaceProxy<jakarta_json_JsonArrayInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly TRUE: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
    /**
     * Original type: 'jakarta.json.JsonValue'
     */
    static readonly FALSE: jakarta_json_JsonValue | JavaInterfaceProxy<jakarta_json_JsonValueInterface> | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonStructureProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonStructureInterface {
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'jakarta.json.JsonValue'
     */
    getValue?(var0: string | null): jakarta_json_JsonValue | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    asJsonObject?(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    asJsonArray?(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): string;
    /**
     * @return original return type: 'jakarta.json.JsonValue$ValueType'
     */
    getValueType(): jakarta_json_JsonValue$ValueType | null;
}
/**
 * Create a proxy for the {@link JsonStructure} interface.
 * All required methods in {@link JsonStructureInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonStructureProxy(methods: JsonStructureInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonStructureInterface>;
declare const JsonStructure_base: typeof JsonStructureClass;
/**
 * Class jakarta.json.JsonStructure.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonStructureClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonStructure extends JsonStructure_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonStructure;
