import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { JsonArray as jakarta_json_JsonArray } from "./JsonArray";
import { JsonValue as jakarta_json_JsonValue } from "./JsonValue";
import { JsonObject as jakarta_json_JsonObject } from "./JsonObject";
import { JsonStructure as jakarta_json_JsonStructure } from "./JsonStructure";
/**
 * This class just defines types, you should import {@link JsonReader} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonReaderClass extends JavaClass {
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    readArray(): Promise<jakarta_json_JsonArray | null>;
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    readArraySync(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue'
     */
    readValue(): Promise<jakarta_json_JsonValue | null>;
    /**
     * @return original return type: 'jakarta.json.JsonValue'
     */
    readValueSync(): jakarta_json_JsonValue | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    readObject(): Promise<jakarta_json_JsonObject | null>;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    readObjectSync(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonStructure'
     */
    read(): Promise<jakarta_json_JsonStructure | null>;
    /**
     * @return original return type: 'jakarta.json.JsonStructure'
     */
    readSync(): jakarta_json_JsonStructure | null;
    /**
     * @return original return type: 'void'
     */
    close(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    closeSync(): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createJsonReaderProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface JsonReaderInterface {
    /**
     * @return original return type: 'jakarta.json.JsonArray'
     */
    readArray(): jakarta_json_JsonArray | null;
    /**
     * @return original return type: 'jakarta.json.JsonValue'
     */
    readValue?(): jakarta_json_JsonValue | null;
    /**
     * @return original return type: 'jakarta.json.JsonObject'
     */
    readObject(): jakarta_json_JsonObject | null;
    /**
     * @return original return type: 'jakarta.json.JsonStructure'
     */
    read(): jakarta_json_JsonStructure | null;
    /**
     * @return original return type: 'void'
     */
    close(): void;
}
/**
 * Create a proxy for the {@link JsonReader} interface.
 * All required methods in {@link JsonReaderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createJsonReaderProxy(methods: JsonReaderInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<JsonReaderInterface>;
declare const JsonReader_base: typeof JsonReaderClass;
/**
 * Class jakarta.json.JsonReader.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonReaderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonReader extends JsonReader_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default JsonReader;
//# sourceMappingURL=JsonReader.d.ts.map