"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemporalUnit = void 0;
exports.createTemporalUnitProxy = createTemporalUnitProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link TemporalUnit} interface.
 * All required methods in {@link TemporalUnitInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createTemporalUnitProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.time.temporal.TemporalUnit', methods, opts);
}
/**
 * Class java.time.temporal.TemporalUnit.
 *
 * This actually imports the java class for further use.
 * The class {@link TemporalUnitClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TemporalUnit extends (0, java_bridge_1.importClass)('java.time.temporal.TemporalUnit') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TemporalUnit = TemporalUnit;
exports.default = TemporalUnit;
