"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileUtil = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.weasis.core.util.FileUtil.
 *
 * This actually imports the java class for further use.
 * The class {@link FileUtilClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FileUtil extends (0, java_bridge_1.importClass)('org.weasis.core.util.FileUtil') {
}
exports.FileUtil = FileUtil;
exports.default = FileUtil;
