"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Arena = void 0;
exports.createArenaProxy = createArenaProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Arena} interface.
 * All required methods in {@link ArenaInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createArenaProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.Arena', methods, opts);
}
/**
 * Class java.lang.foreign.Arena.
 *
 * This actually imports the java class for further use.
 * The class {@link ArenaClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Arena extends (0, java_bridge_1.importClass)('java.lang.foreign.Arena') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Arena = Arena;
exports.default = Arena;
