"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupLayout = void 0;
exports.createGroupLayoutProxy = createGroupLayoutProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link GroupLayout} interface.
 * All required methods in {@link GroupLayoutInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createGroupLayoutProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.GroupLayout', methods, opts);
}
/**
 * Class java.lang.foreign.GroupLayout.
 *
 * This actually imports the java class for further use.
 * The class {@link GroupLayoutClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class GroupLayout extends (0, java_bridge_1.importClass)('java.lang.foreign.GroupLayout') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.GroupLayout = GroupLayout;
exports.default = GroupLayout;
