import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Optional as java_util_Optional } from "./../../util/Optional";
import { ByteBuffer as java_nio_ByteBuffer } from "./../../nio/ByteBuffer";
import { MemorySegment$Scope as java_lang_foreign_MemorySegment$Scope } from "./MemorySegment$Scope";
import { ValueLayout$OfLong as java_lang_foreign_ValueLayout$OfLong, ValueLayout$OfLongInterface as java_lang_foreign_ValueLayout$OfLongInterface } from "./ValueLayout$OfLong";
import { Long as java_lang_Long } from "./../Long";
import { ValueLayout$OfChar as java_lang_foreign_ValueLayout$OfChar, ValueLayout$OfCharInterface as java_lang_foreign_ValueLayout$OfCharInterface } from "./ValueLayout$OfChar";
import { AddressLayout as java_lang_foreign_AddressLayout, AddressLayoutInterface as java_lang_foreign_AddressLayoutInterface } from "./AddressLayout";
import { ValueLayout$OfFloat as java_lang_foreign_ValueLayout$OfFloat, ValueLayout$OfFloatInterface as java_lang_foreign_ValueLayout$OfFloatInterface } from "./ValueLayout$OfFloat";
import { ValueLayout$OfDouble as java_lang_foreign_ValueLayout$OfDouble, ValueLayout$OfDoubleInterface as java_lang_foreign_ValueLayout$OfDoubleInterface } from "./ValueLayout$OfDouble";
import { ValueLayout$OfShort as java_lang_foreign_ValueLayout$OfShort, ValueLayout$OfShortInterface as java_lang_foreign_ValueLayout$OfShortInterface } from "./ValueLayout$OfShort";
import { ValueLayout$OfByte as java_lang_foreign_ValueLayout$OfByte, ValueLayout$OfByteInterface as java_lang_foreign_ValueLayout$OfByteInterface } from "./ValueLayout$OfByte";
import { ValueLayout$OfBoolean as java_lang_foreign_ValueLayout$OfBoolean, ValueLayout$OfBooleanInterface as java_lang_foreign_ValueLayout$OfBooleanInterface } from "./ValueLayout$OfBoolean";
import { ValueLayout$OfInt as java_lang_foreign_ValueLayout$OfInt, ValueLayout$OfIntInterface as java_lang_foreign_ValueLayout$OfIntInterface } from "./ValueLayout$OfInt";
import { ValueLayout as java_lang_foreign_ValueLayout, ValueLayoutInterface as java_lang_foreign_ValueLayoutInterface } from "./ValueLayout";
import { Integer as java_lang_Integer } from "./../Integer";
import { Double as java_lang_Double } from "./../Double";
import { Byte as java_lang_Byte } from "./../Byte";
import { Short as java_lang_Short } from "./../Short";
import { Boolean as java_lang_Boolean } from "./../Boolean";
import { Float as java_lang_Float } from "./../Float";
import { Spliterator as java_util_Spliterator } from "./../../util/Spliterator";
import { MemoryLayout as java_lang_foreign_MemoryLayout, MemoryLayoutInterface as java_lang_foreign_MemoryLayoutInterface } from "./MemoryLayout";
import { Buffer as java_nio_Buffer } from "./../../nio/Buffer";
import { Thread as java_lang_Thread } from "./../Thread";
import { Arena as java_lang_foreign_Arena, ArenaInterface as java_lang_foreign_ArenaInterface } from "./Arena";
import { Consumer as java_util_function_Consumer, ConsumerInterface as java_util_function_ConsumerInterface } from "./../../util/function/Consumer";
import { Stream as java_util_stream_Stream } from "./../../util/stream/Stream";
/**
 * This class just defines types, you should import {@link MemorySegment} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MemorySegmentClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asReadOnly(): Promise<MemorySegment | null>;
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asReadOnlySync(): MemorySegment | null;
    /**
     * @return original return type: 'java.util.Optional'
     */
    heapBase(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    heapBaseSync(): java_util_Optional | null;
    /**
     * @return original return type: 'long'
     */
    byteSize(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    byteSizeSync(): number;
    /**
     * @return original return type: 'boolean'
     */
    isMapped(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isMappedSync(): boolean;
    /**
     * @return original return type: 'java.nio.ByteBuffer'
     */
    asByteBuffer(): Promise<java_nio_ByteBuffer | null>;
    /**
     * @return original return type: 'java.nio.ByteBuffer'
     */
    asByteBufferSync(): java_nio_ByteBuffer | null;
    /**
     * @return original return type: 'boolean'
     */
    isLoaded(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isLoadedSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    segmentOffset(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    segmentOffsetSync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): number;
    /**
     * @return original return type: 'boolean'
     */
    isNative(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNativeSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnly(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnlySync(): boolean;
    /**
     * @return original return type: 'void'
     */
    load(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    loadSync(): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment$Scope'
     */
    scope(): Promise<java_lang_foreign_MemorySegment$Scope | null>;
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment$Scope'
     */
    scopeSync(): java_lang_foreign_MemorySegment$Scope | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    get(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    get(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): string | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    get(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    getSync(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    get(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    get(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    get(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    get(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    get(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    get(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    getSync(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @return original return type: 'long[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null): Promise<(number)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @return original return type: 'long[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @return original return type: 'double[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null): Promise<(number)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @return original return type: 'double[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @return original return type: 'int[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null): Promise<(number)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @return original return type: 'int[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @return original return type: 'char[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null): Promise<(string | null)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @return original return type: 'char[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null): (string | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @return original return type: 'short[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null): Promise<(number)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @return original return type: 'short[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @return original return type: 'byte[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null): Promise<Buffer | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @return original return type: 'byte[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null): Buffer | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @return original return type: 'float[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null): Promise<(number)[] | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @return original return type: 'float[]'
     */
    toArraySync(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null): (number)[] | null;
    /**
     * @return original return type: 'void'
     */
    unload(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    unloadSync(): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'java.lang.foreign.ValueLayout'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.Object'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'void'
     */
    static copy(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var2: java_lang_Long | bigint | number, var3: BasicOrJavaType | null, var4: java_lang_Integer | number, var5: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'java.lang.foreign.ValueLayout'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.Object'
     * @param var4 original type: 'int'
     * @param var5 original type: 'int'
     * @return original return type: 'void'
     */
    static copySync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var2: java_lang_Long | bigint | number, var3: BasicOrJavaType | null, var4: java_lang_Integer | number, var5: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'java.lang.foreign.ValueLayout'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.foreign.MemorySegment'
     * @param var4 original type: 'java.lang.foreign.ValueLayout'
     * @param var5 original type: 'long'
     * @param var6 original type: 'long'
     * @return original return type: 'void'
     */
    static copy(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var2: java_lang_Long | bigint | number, var3: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var4: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var5: java_lang_Long | bigint | number, var6: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'java.lang.foreign.ValueLayout'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.foreign.MemorySegment'
     * @param var4 original type: 'java.lang.foreign.ValueLayout'
     * @param var5 original type: 'long'
     * @param var6 original type: 'long'
     * @return original return type: 'void'
     */
    static copySync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var2: java_lang_Long | bigint | number, var3: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var4: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var5: java_lang_Long | bigint | number, var6: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @param var3 original type: 'long'
     * @param var4 original type: 'long'
     * @return original return type: 'void'
     */
    static copy(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var3: java_lang_Long | bigint | number, var4: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @param var3 original type: 'long'
     * @param var4 original type: 'long'
     * @return original return type: 'void'
     */
    static copySync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var3: java_lang_Long | bigint | number, var4: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'int'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @param var3 original type: 'java.lang.foreign.ValueLayout'
     * @param var4 original type: 'long'
     * @param var5 original type: 'int'
     * @return original return type: 'void'
     */
    static copy(var0: BasicOrJavaType | null, var1: java_lang_Integer | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var3: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var4: java_lang_Long | bigint | number, var5: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'int'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @param var3 original type: 'java.lang.foreign.ValueLayout'
     * @param var4 original type: 'long'
     * @param var5 original type: 'int'
     * @return original return type: 'void'
     */
    static copySync(var0: BasicOrJavaType | null, var1: java_lang_Integer | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var3: java_lang_foreign_ValueLayout | JavaInterfaceProxy<java_lang_foreign_ValueLayoutInterface> | null, var4: java_lang_Long | bigint | number, var5: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): string | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    getAtIndex(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    getAtIndexSync(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    getAtIndex(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    getAtIndexSync(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    set(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    setSync(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): void;
    /**
     * @return original return type: 'long'
     */
    address(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    addressSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setUtf8String(var0: java_lang_Long | bigint | number, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setUtf8StringSync(var0: java_lang_Long | bigint | number, var1: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.Spliterator'
     */
    spliterator(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): Promise<java_util_Spliterator | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.Spliterator'
     */
    spliteratorSync(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): java_util_Spliterator | null;
    /**
     * @param var0 original type: 'java.nio.Buffer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofBuffer(var0: java_nio_Buffer | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'java.nio.Buffer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofBufferSync(var0: java_nio_Buffer | null): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.Thread'
     * @return original return type: 'boolean'
     */
    isAccessibleBy(var0: java_lang_Thread | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Thread'
     * @return original return type: 'boolean'
     */
    isAccessibleBySync(var0: java_lang_Thread | null): boolean;
    /**
     * @param var0 original type: 'int[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (java_lang_Integer | number)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'int[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (java_lang_Integer | number)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (string | null)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'char[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (string | null)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'short[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (java_lang_Short | number)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'short[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (java_lang_Short | number)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'double[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (java_lang_Double | number)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'double[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (java_lang_Double | number)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: Buffer | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: Buffer | null): MemorySegment | null;
    /**
     * @param var0 original type: 'float[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (java_lang_Float | number)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'float[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (java_lang_Float | number)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArray(var0: (java_lang_Long | bigint | number)[] | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long[]'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofArraySync(var0: (java_lang_Long | bigint | number)[] | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofAddress(var0: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    static ofAddressSync(var0: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'byte'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    fill(var0: java_lang_Byte | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'byte'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    fillSync(var0: java_lang_Byte | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    copyFrom(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    copyFromSync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.Arena'
     * @param var2 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var2: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.Arena'
     * @param var2 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpretSync(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var2: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpretSync(var0: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.Arena'
     * @param var1 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var1: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.Arena'
     * @param var1 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpretSync(var0: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var1: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.foreign.MemorySegment'
     * @param var4 original type: 'long'
     * @param var5 original type: 'long'
     * @return original return type: 'long'
     */
    static mismatch(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number, var3: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var4: java_lang_Long | bigint | number, var5: java_lang_Long | bigint | number): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @param var3 original type: 'java.lang.foreign.MemorySegment'
     * @param var4 original type: 'long'
     * @param var5 original type: 'long'
     * @return original return type: 'long'
     */
    static mismatchSync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number, var3: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null, var4: java_lang_Long | bigint | number, var5: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    mismatch(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    mismatchSync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): number;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.stream.Stream'
     */
    elements(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): Promise<java_util_stream_Stream | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.stream.Stream'
     */
    elementsSync(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): java_util_stream_Stream | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    setAtIndex(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    setAtIndexSync(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): void;
    /**
     * @return original return type: 'void'
     */
    force(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    forceSync(): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.util.Optional'
     */
    asOverlappingSlice(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): Promise<java_util_Optional | null>;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.util.Optional'
     */
    asOverlappingSliceSync(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): java_util_Optional | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.String'
     */
    getUtf8String(var0: java_lang_Long | bigint | number): Promise<string | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.String'
     */
    getUtf8StringSync(var0: java_lang_Long | bigint | number): string | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice(var0: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSliceSync(var0: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSliceSync(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSliceSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): Promise<MemorySegment | null>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSliceSync(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * Original type: 'java.lang.foreign.MemorySegment'
     */
    static readonly NULL: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createMemorySegmentProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface MemorySegmentInterface {
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asReadOnly(): MemorySegment | null;
    /**
     * @return original return type: 'java.util.Optional'
     */
    heapBase(): java_util_Optional | null;
    /**
     * @return original return type: 'long'
     */
    byteSize(): number;
    /**
     * @return original return type: 'boolean'
     */
    isMapped(): boolean;
    /**
     * @return original return type: 'java.nio.ByteBuffer'
     */
    asByteBuffer(): java_nio_ByteBuffer | null;
    /**
     * @return original return type: 'boolean'
     */
    isLoaded(): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    segmentOffset(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): number;
    /**
     * @return original return type: 'boolean'
     */
    isNative(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isReadOnly(): boolean;
    /**
     * @return original return type: 'void'
     */
    load(): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): number;
    /**
     * @return original return type: 'java.lang.foreign.MemorySegment$Scope'
     */
    scope(): java_lang_foreign_MemorySegment$Scope | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): string | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    get?(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    get?(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @return original return type: 'long[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @return original return type: 'double[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @return original return type: 'int[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @return original return type: 'char[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null): (string | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @return original return type: 'short[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null): (number)[] | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @return original return type: 'byte[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null): Buffer | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @return original return type: 'float[]'
     */
    toArray(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null): (number)[] | null;
    /**
     * @return original return type: 'void'
     */
    unload(): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @return original return type: 'float'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @return original return type: 'char'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number): string | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    getAtIndex?(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @return original return type: 'double'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @return original return type: 'short'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @return original return type: 'long'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @return original return type: 'byte'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @return original return type: 'int'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number): number;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @return original return type: 'boolean'
     */
    getAtIndex?(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    set?(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): void;
    /**
     * @return original return type: 'long'
     */
    address(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setUtf8String?(var0: java_lang_Long | bigint | number, var1: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.Spliterator'
     */
    spliterator(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): java_util_Spliterator | null;
    /**
     * @param var0 original type: 'java.lang.Thread'
     * @return original return type: 'boolean'
     */
    isAccessibleBy(var0: java_lang_Thread | null): boolean;
    /**
     * @param var0 original type: 'byte'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    fill(var0: java_lang_Byte | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    copyFrom?(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.Arena'
     * @param var2 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var2: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.foreign.Arena'
     * @param var1 original type: 'java.util.function.Consumer'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    reinterpret(var0: java_lang_foreign_Arena | JavaInterfaceProxy<java_lang_foreign_ArenaInterface> | null, var1: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): MemorySegment | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'long'
     */
    mismatch?(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): number;
    /**
     * @param var0 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.util.stream.Stream'
     */
    elements(var0: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): java_util_stream_Stream | null;
    /**
     * @param var0 original type: 'java.lang.foreign.AddressLayout'
     * @param var1 original type: 'long'
     * @param var2 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_AddressLayout | JavaInterfaceProxy<java_lang_foreign_AddressLayoutInterface> | null, var1: java_lang_Long | bigint | number, var2: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfChar'
     * @param var1 original type: 'long'
     * @param var2 original type: 'char'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfChar | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfCharInterface> | null, var1: java_lang_Long | bigint | number, var2: string | null): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfFloat'
     * @param var1 original type: 'long'
     * @param var2 original type: 'float'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfFloat | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfFloatInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Float | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfBoolean'
     * @param var1 original type: 'long'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfBoolean | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfBooleanInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfShort'
     * @param var1 original type: 'long'
     * @param var2 original type: 'short'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfShort | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfShortInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Short | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfInt'
     * @param var1 original type: 'long'
     * @param var2 original type: 'int'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfInt | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfIntInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfByte'
     * @param var1 original type: 'long'
     * @param var2 original type: 'byte'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfByte | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfByteInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Byte | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfLong'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfLong | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfLongInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.foreign.ValueLayout$OfDouble'
     * @param var1 original type: 'long'
     * @param var2 original type: 'double'
     * @return original return type: 'void'
     */
    setAtIndex?(var0: java_lang_foreign_ValueLayout$OfDouble | JavaInterfaceProxy<java_lang_foreign_ValueLayout$OfDoubleInterface> | null, var1: java_lang_Long | bigint | number, var2: java_lang_Double | number): void;
    /**
     * @return original return type: 'void'
     */
    force(): void;
    /**
     * @param var0 original type: 'java.lang.foreign.MemorySegment'
     * @return original return type: 'java.util.Optional'
     */
    asOverlappingSlice(var0: MemorySegmentClass | JavaInterfaceProxy<MemorySegmentInterface> | null): java_util_Optional | null;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.String'
     */
    getUtf8String?(var0: java_lang_Long | bigint | number): string | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice?(var0: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'java.lang.foreign.MemoryLayout'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice?(var0: java_lang_Long | bigint | number, var1: java_lang_foreign_MemoryLayout | JavaInterfaceProxy<java_lang_foreign_MemoryLayoutInterface> | null): MemorySegment | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @param var2 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice?(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number, var2: java_lang_Long | bigint | number): MemorySegment | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'long'
     * @param var1 original type: 'long'
     * @return original return type: 'java.lang.foreign.MemorySegment'
     */
    asSlice?(var0: java_lang_Long | bigint | number, var1: java_lang_Long | bigint | number): MemorySegment | null;
}
/**
 * Create a proxy for the {@link MemorySegment} interface.
 * All required methods in {@link MemorySegmentInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createMemorySegmentProxy(methods: MemorySegmentInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<MemorySegmentInterface>;
declare const MemorySegment_base: typeof MemorySegmentClass;
/**
 * Class java.lang.foreign.MemorySegment.
 *
 * This actually imports the java class for further use.
 * The class {@link MemorySegmentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MemorySegment extends MemorySegment_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default MemorySegment;
//# sourceMappingURL=MemorySegment.d.ts.map