import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
/**
 * This class just defines types, you should import {@link MemorySegment$Scope} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MemorySegment$ScopeClass extends JavaClass {
    /**
     * @return original return type: 'boolean'
     */
    isAlive(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAliveSync(): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createMemorySegment$ScopeProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface MemorySegment$ScopeInterface {
    /**
     * @return original return type: 'boolean'
     */
    isAlive(): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): boolean;
}
/**
 * Create a proxy for the {@link MemorySegment$Scope} interface.
 * All required methods in {@link MemorySegment$ScopeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createMemorySegment$ScopeProxy(methods: MemorySegment$ScopeInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<MemorySegment$ScopeInterface>;
declare const MemorySegment$Scope_base: typeof MemorySegment$ScopeClass;
/**
 * Class java.lang.foreign.MemorySegment$Scope.
 *
 * This actually imports the java class for further use.
 * The class {@link MemorySegment$ScopeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class MemorySegment$Scope extends MemorySegment$Scope_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default MemorySegment$Scope;
