"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MemorySegment$Scope = void 0;
exports.createMemorySegment$ScopeProxy = createMemorySegment$ScopeProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link MemorySegment$Scope} interface.
 * All required methods in {@link MemorySegment$ScopeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMemorySegment$ScopeProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.MemorySegment$Scope', methods, opts);
}
/**
 * Class java.lang.foreign.MemorySegment$Scope.
 *
 * This actually imports the java class for further use.
 * The class {@link MemorySegment$ScopeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class MemorySegment$Scope extends (0, java_bridge_1.importClass)('java.lang.foreign.MemorySegment$Scope') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.MemorySegment$Scope = MemorySegment$Scope;
exports.default = MemorySegment$Scope;
