"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnionLayout = void 0;
exports.createUnionLayoutProxy = createUnionLayoutProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link UnionLayout} interface.
 * All required methods in {@link UnionLayoutInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createUnionLayoutProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.UnionLayout', methods, opts);
}
/**
 * Class java.lang.foreign.UnionLayout.
 *
 * This actually imports the java class for further use.
 * The class {@link UnionLayoutClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class UnionLayout extends (0, java_bridge_1.importClass)('java.lang.foreign.UnionLayout') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.UnionLayout = UnionLayout;
exports.default = UnionLayout;
