"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueLayout$OfBoolean = void 0;
exports.createValueLayout$OfBooleanProxy = createValueLayout$OfBooleanProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValueLayout$OfBoolean} interface.
 * All required methods in {@link ValueLayout$OfBooleanInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValueLayout$OfBooleanProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.ValueLayout$OfBoolean', methods, opts);
}
/**
 * Class java.lang.foreign.ValueLayout$OfBoolean.
 *
 * This actually imports the java class for further use.
 * The class {@link ValueLayout$OfBooleanClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValueLayout$OfBoolean extends (0, java_bridge_1.importClass)('java.lang.foreign.ValueLayout$OfBoolean') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValueLayout$OfBoolean = ValueLayout$OfBoolean;
exports.default = ValueLayout$OfBoolean;
