"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueLayout$OfLong = void 0;
exports.createValueLayout$OfLongProxy = createValueLayout$OfLongProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValueLayout$OfLong} interface.
 * All required methods in {@link ValueLayout$OfLongInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValueLayout$OfLongProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.ValueLayout$OfLong', methods, opts);
}
/**
 * Class java.lang.foreign.ValueLayout$OfLong.
 *
 * This actually imports the java class for further use.
 * The class {@link ValueLayout$OfLongClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValueLayout$OfLong extends (0, java_bridge_1.importClass)('java.lang.foreign.ValueLayout$OfLong') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValueLayout$OfLong = ValueLayout$OfLong;
exports.default = ValueLayout$OfLong;
