"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueLayout$OfInt = void 0;
exports.createValueLayout$OfIntProxy = createValueLayout$OfIntProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValueLayout$OfInt} interface.
 * All required methods in {@link ValueLayout$OfIntInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValueLayout$OfIntProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.ValueLayout$OfInt', methods, opts);
}
/**
 * Class java.lang.foreign.ValueLayout$OfInt.
 *
 * This actually imports the java class for further use.
 * The class {@link ValueLayout$OfIntClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValueLayout$OfInt extends (0, java_bridge_1.importClass)('java.lang.foreign.ValueLayout$OfInt') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValueLayout$OfInt = ValueLayout$OfInt;
exports.default = ValueLayout$OfInt;
