"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueLayout$OfFloat = void 0;
exports.createValueLayout$OfFloatProxy = createValueLayout$OfFloatProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValueLayout$OfFloat} interface.
 * All required methods in {@link ValueLayout$OfFloatInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValueLayout$OfFloatProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.ValueLayout$OfFloat', methods, opts);
}
/**
 * Class java.lang.foreign.ValueLayout$OfFloat.
 *
 * This actually imports the java class for further use.
 * The class {@link ValueLayout$OfFloatClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValueLayout$OfFloat extends (0, java_bridge_1.importClass)('java.lang.foreign.ValueLayout$OfFloat') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValueLayout$OfFloat = ValueLayout$OfFloat;
exports.default = ValueLayout$OfFloat;
