"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueLayout$OfChar = void 0;
exports.createValueLayout$OfCharProxy = createValueLayout$OfCharProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValueLayout$OfChar} interface.
 * All required methods in {@link ValueLayout$OfCharInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValueLayout$OfCharProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.foreign.ValueLayout$OfChar', methods, opts);
}
/**
 * Class java.lang.foreign.ValueLayout$OfChar.
 *
 * This actually imports the java class for further use.
 * The class {@link ValueLayout$OfCharClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValueLayout$OfChar extends (0, java_bridge_1.importClass)('java.lang.foreign.ValueLayout$OfChar') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValueLayout$OfChar = ValueLayout$OfChar;
exports.default = ValueLayout$OfChar;
