"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Enumeration = void 0;
exports.createEnumerationProxy = createEnumerationProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Enumeration} interface.
 * All required methods in {@link EnumerationInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createEnumerationProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.Enumeration', methods, opts);
}
/**
 * Class java.util.Enumeration.
 *
 * This actually imports the java class for further use.
 * The class {@link EnumerationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Enumeration extends (0, java_bridge_1.importClass)('java.util.Enumeration') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Enumeration = Enumeration;
exports.default = Enumeration;
