"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SequencedCollection = void 0;
exports.createSequencedCollectionProxy = createSequencedCollectionProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link SequencedCollection} interface.
 * All required methods in {@link SequencedCollectionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSequencedCollectionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.SequencedCollection', methods, opts);
}
/**
 * Class java.util.SequencedCollection.
 *
 * This actually imports the java class for further use.
 * The class {@link SequencedCollectionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SequencedCollection extends (0, java_bridge_1.importClass)('java.util.SequencedCollection') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.SequencedCollection = SequencedCollection;
exports.default = SequencedCollection;
