import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { MatOfInt as org_opencv_core_MatOfInt } from "./../core/MatOfInt";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../java/util/List";
import { Scalar as org_opencv_core_Scalar } from "./../core/Scalar";
/**
 * This class just defines types, you should import {@link Animation} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class AnimationClass extends JavaClass {
    /**
     * @return original return type: 'long'
     */
    getNativeObjAddr(): Promise<number>;
    /**
     * @return original return type: 'long'
     */
    getNativeObjAddrSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @return original return type: 'org.opencv.core.MatOfInt'
     */
    get_durations(): Promise<org_opencv_core_MatOfInt | null>;
    /**
     * @return original return type: 'org.opencv.core.MatOfInt'
     */
    get_durationsSync(): org_opencv_core_MatOfInt | null;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'java.util.List'
     */
    get_frames(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    get_framesSync(): java_util_List | null;
    /**
     * @return original return type: 'org.opencv.core.Scalar'
     */
    get_bgcolor(): Promise<org_opencv_core_Scalar | null>;
    /**
     * @return original return type: 'org.opencv.core.Scalar'
     */
    get_bgcolorSync(): org_opencv_core_Scalar | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    set_loop_count(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    set_loop_countSync(var0: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'int'
     */
    get_loop_count(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    get_loop_countSync(): number;
    /**
     * @param var0 original type: 'org.opencv.core.Scalar'
     * @return original return type: 'void'
     */
    set_bgcolor(var0: org_opencv_core_Scalar | null): Promise<void>;
    /**
     * @param var0 original type: 'org.opencv.core.Scalar'
     * @return original return type: 'void'
     */
    set_bgcolorSync(var0: org_opencv_core_Scalar | null): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'org.opencv.core.MatOfInt'
     * @return original return type: 'void'
     */
    set_durations(var0: org_opencv_core_MatOfInt | null): Promise<void>;
    /**
     * @param var0 original type: 'org.opencv.core.MatOfInt'
     * @return original return type: 'void'
     */
    set_durationsSync(var0: org_opencv_core_MatOfInt | null): void;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    set_frames(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    set_framesSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'org.opencv.imgcodecs.Animation'
     */
    static __fromPtr__(var0: java_lang_Long | bigint | number): Promise<Animation | null>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'org.opencv.imgcodecs.Animation'
     */
    static __fromPtr__Sync(var0: java_lang_Long | bigint | number): Animation | null;
}
declare const Animation_base: typeof AnimationClass;
/**
 * Class org.opencv.imgcodecs.Animation.
 *
 * This actually imports the java class for further use.
 * The class {@link AnimationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Animation extends Animation_base {
}
export default Animation;
