"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Animation = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.opencv.imgcodecs.Animation.
 *
 * This actually imports the java class for further use.
 * The class {@link AnimationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Animation extends (0, java_bridge_1.importClass)('org.opencv.imgcodecs.Animation') {
}
exports.Animation = Animation;
exports.default = Animation;
