"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Callable = void 0;
exports.createCallableProxy = createCallableProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Callable} interface.
 * All required methods in {@link CallableInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createCallableProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.concurrent.Callable', methods, opts);
}
/**
 * Class java.util.concurrent.Callable.
 *
 * This actually imports the java class for further use.
 * The class {@link CallableClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Callable extends (0, java_bridge_1.importClass)('java.util.concurrent.Callable') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Callable = Callable;
exports.default = Callable;
