"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Future$State = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.util.concurrent.Future$State.
 *
 * This actually imports the java class for further use.
 * The class {@link Future$StateClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Future$State extends (0, java_bridge_1.importClass)('java.util.concurrent.Future$State') {
}
exports.Future$State = Future$State;
exports.default = Future$State;
