import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Thread as java_lang_Thread } from "./../../lang/Thread";
import { Runnable as java_lang_Runnable, RunnableInterface as java_lang_RunnableInterface } from "./../../lang/Runnable";
/**
 * This class just defines types, you should import {@link ThreadFactory} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ThreadFactoryClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.Runnable'
     * @return original return type: 'java.lang.Thread'
     */
    newThread(var0: java_lang_Runnable | JavaInterfaceProxy<java_lang_RunnableInterface> | null): Promise<java_lang_Thread | null>;
    /**
     * @param var0 original type: 'java.lang.Runnable'
     * @return original return type: 'java.lang.Thread'
     */
    newThreadSync(var0: java_lang_Runnable | JavaInterfaceProxy<java_lang_RunnableInterface> | null): java_lang_Thread | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createThreadFactoryProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface ThreadFactoryInterface {
    /**
     * @param var0 original type: 'java.lang.Runnable'
     * @return original return type: 'java.lang.Thread'
     */
    newThread(var0: java_lang_Runnable | JavaInterfaceProxy<java_lang_RunnableInterface> | null): java_lang_Thread | null;
}
/**
 * Create a proxy for the {@link ThreadFactory} interface.
 * All required methods in {@link ThreadFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createThreadFactoryProxy(methods: ThreadFactoryInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<ThreadFactoryInterface>;
declare const ThreadFactory_base: typeof ThreadFactoryClass;
/**
 * Class java.util.concurrent.ThreadFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link ThreadFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ThreadFactory extends ThreadFactory_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default ThreadFactory;
//# sourceMappingURL=ThreadFactory.d.ts.map