"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThreadFactory = exports.createThreadFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ThreadFactory} interface.
 * All required methods in {@link ThreadFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createThreadFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.util.concurrent.ThreadFactory', methods, opts);
}
exports.createThreadFactoryProxy = createThreadFactoryProxy;
/**
 * Class java.util.concurrent.ThreadFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link ThreadFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ThreadFactory extends (0, java_bridge_1.importClass)('java.util.concurrent.ThreadFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ThreadFactory = ThreadFactory;
exports.default = ThreadFactory;
