"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Location = exports.createLocationProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Location} interface.
 * All required methods in {@link LocationInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createLocationProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.xml.stream.Location', methods, opts);
}
exports.createLocationProxy = createLocationProxy;
/**
 * Class javax.xml.stream.Location.
 *
 * This actually imports the java class for further use.
 * The class {@link LocationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Location extends (0, java_bridge_1.importClass)('javax.xml.stream.Location') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Location = Location;
exports.default = Location;
