"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.XMLStreamReader = void 0;
exports.createXMLStreamReaderProxy = createXMLStreamReaderProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link XMLStreamReader} interface.
 * All required methods in {@link XMLStreamReaderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createXMLStreamReaderProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.xml.stream.XMLStreamReader', methods, opts);
}
/**
 * Class javax.xml.stream.XMLStreamReader.
 *
 * This actually imports the java class for further use.
 * The class {@link XMLStreamReaderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class XMLStreamReader extends (0, java_bridge_1.importClass)('javax.xml.stream.XMLStreamReader') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.XMLStreamReader = XMLStreamReader;
exports.default = XMLStreamReader;
