"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoCloseable = void 0;
exports.createAutoCloseableProxy = createAutoCloseableProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link AutoCloseable} interface.
 * All required methods in {@link AutoCloseableInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createAutoCloseableProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.AutoCloseable', methods, opts);
}
/**
 * Class java.lang.AutoCloseable.
 *
 * This actually imports the java class for further use.
 * The class {@link AutoCloseableClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AutoCloseable extends (0, java_bridge_1.importClass)('java.lang.AutoCloseable') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.AutoCloseable = AutoCloseable;
exports.default = AutoCloseable;
