"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Runnable = void 0;
exports.createRunnableProxy = createRunnableProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Runnable} interface.
 * All required methods in {@link RunnableInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createRunnableProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.Runnable', methods, opts);
}
/**
 * Class java.lang.Runnable.
 *
 * This actually imports the java class for further use.
 * The class {@link RunnableClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Runnable extends (0, java_bridge_1.importClass)('java.lang.Runnable') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Runnable = Runnable;
exports.default = Runnable;
