"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Thread$Builder = void 0;
exports.createThread$BuilderProxy = createThread$BuilderProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Thread$Builder} interface.
 * All required methods in {@link Thread$BuilderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createThread$BuilderProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('java.lang.Thread$Builder', methods, opts);
}
/**
 * Class java.lang.Thread$Builder.
 *
 * This actually imports the java class for further use.
 * The class {@link Thread$BuilderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Thread$Builder extends (0, java_bridge_1.importClass)('java.lang.Thread$Builder') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Thread$Builder = Thread$Builder;
exports.default = Thread$Builder;
