"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NamespaceContext = exports.createNamespaceContextProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link NamespaceContext} interface.
 * All required methods in {@link NamespaceContextInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createNamespaceContextProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.xml.namespace.NamespaceContext', methods, opts);
}
exports.createNamespaceContextProxy = createNamespaceContextProxy;
/**
 * Class javax.xml.namespace.NamespaceContext.
 *
 * This actually imports the java class for further use.
 * The class {@link NamespaceContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class NamespaceContext extends (0, java_bridge_1.importClass)('javax.xml.namespace.NamespaceContext') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.NamespaceContext = NamespaceContext;
exports.default = NamespaceContext;
