import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { WlPresentation as org_weasis_opencv_op_lut_WlPresentation, WlPresentationInterface as org_weasis_opencv_op_lut_WlPresentationInterface } from "./../../weasis/opencv/op/lut/WlPresentation";
import { PrDicomObject as org_dcm4che3_img_data_PrDicomObject } from "./data/PrDicomObject";
import { LutShape as org_weasis_opencv_op_lut_LutShape } from "./../../weasis/opencv/op/lut/LutShape";
import { PresetWindowLevel as org_dcm4che3_img_lut_PresetWindowLevel } from "./lut/PresetWindowLevel";
import { LookupTableCV as org_weasis_opencv_data_LookupTableCV } from "./../../weasis/opencv/data/LookupTableCV";
import { WlParams as org_weasis_opencv_op_lut_WlParams, WlParamsInterface as org_weasis_opencv_op_lut_WlParamsInterface } from "./../../weasis/opencv/op/lut/WlParams";
import { ImageDescriptor as org_dcm4che3_img_stream_ImageDescriptor } from "./stream/ImageDescriptor";
import { List as java_util_List } from "./../../../java/util/List";
import { Boolean as java_lang_Boolean } from "./../../../java/lang/Boolean";
import { Number as java_lang_Number } from "./../../../java/lang/Number";
import { Core$MinMaxLocResult as org_opencv_core_Core$MinMaxLocResult } from "./../../opencv/core/Core$MinMaxLocResult";
import { PresentationStateLut as org_weasis_opencv_op_lut_PresentationStateLut, PresentationStateLutInterface as org_weasis_opencv_op_lut_PresentationStateLutInterface } from "./../../weasis/opencv/op/lut/PresentationStateLut";
import { LutParameters as org_weasis_opencv_op_lut_LutParameters } from "./../../weasis/opencv/op/lut/LutParameters";
import { PlanarImage as org_weasis_opencv_data_PlanarImage, PlanarImageInterface as org_weasis_opencv_data_PlanarImageInterface } from "./../../weasis/opencv/data/PlanarImage";
/**
 * This class just defines types, you should import {@link DicomImageAdapter} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DicomImageAdapterClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getFullDynamicCenter(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getFullDynamicCenterSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getMaxValue(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getMaxValueSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setBitsStored(var0: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'void'
     */
    setBitsStoredSync(var0: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'double'
     */
    getRescaleIntercept(var0: org_dcm4che3_img_data_PrDicomObject | null): Promise<number>;
    /**
     * @param var0 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'double'
     */
    getRescaleInterceptSync(var0: org_dcm4che3_img_data_PrDicomObject | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    getDefaultShape(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<org_weasis_opencv_op_lut_LutShape | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'org.weasis.opencv.op.lut.LutShape'
     */
    getDefaultShapeSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): org_weasis_opencv_op_lut_LutShape | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'int'
     */
    getMaxAllocatedValue(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'int'
     */
    getMaxAllocatedValueSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'boolean'
     */
    isModalityLutOutSigned(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'boolean'
     */
    isModalityLutOutSignedSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): boolean;
    /**
     * @return original return type: 'int'
     */
    getBitsStored(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getBitsStoredSync(): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'org.dcm4che3.img.lut.PresetWindowLevel'
     */
    getDefaultPreset(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<org_dcm4che3_img_lut_PresetWindowLevel | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'org.dcm4che3.img.lut.PresetWindowLevel'
     */
    getDefaultPresetSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): org_dcm4che3_img_lut_PresetWindowLevel | null;
    /**
     * @param var0 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'double'
     */
    getRescaleSlope(var0: org_dcm4che3_img_data_PrDicomObject | null): Promise<number>;
    /**
     * @param var0 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'double'
     */
    getRescaleSlopeSync(var0: org_dcm4che3_img_data_PrDicomObject | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getDefaultLevel(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getDefaultLevelSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlParams'
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getVOILookup(var0: org_weasis_opencv_op_lut_WlParams | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlParamsInterface> | null): Promise<org_weasis_opencv_data_LookupTableCV | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlParams'
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getVOILookupSync(var0: org_weasis_opencv_op_lut_WlParams | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlParamsInterface> | null): org_weasis_opencv_data_LookupTableCV | null;
    /**
     * @return original return type: 'int'
     */
    getPresetCollectionSize(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getPresetCollectionSizeSync(): number;
    /**
     * @return original return type: 'org.dcm4che3.img.stream.ImageDescriptor'
     */
    getImageDescriptor(): Promise<org_dcm4che3_img_stream_ImageDescriptor | null>;
    /**
     * @return original return type: 'org.dcm4che3.img.stream.ImageDescriptor'
     */
    getImageDescriptorSync(): org_dcm4che3_img_stream_ImageDescriptor | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.util.List'
     */
    getPresetList(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.util.List'
     */
    getPresetListSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getPresetList(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var1: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getPresetListSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var1: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'java.lang.Number'
     * @param var1 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.lang.Number'
     */
    pixelToRealValue(var0: java_lang_Number | null, var1: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<java_lang_Number | null>;
    /**
     * @param var0 original type: 'java.lang.Number'
     * @param var1 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'java.lang.Number'
     */
    pixelToRealValueSync(var0: java_lang_Number | null, var1: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): java_lang_Number | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'int'
     */
    getMinAllocatedValue(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'int'
     */
    getMinAllocatedValueSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getMinValue(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getMinValueSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getFullDynamicWidth(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getFullDynamicWidthSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @return original return type: 'org.opencv.core.Core$MinMaxLocResult'
     */
    getMinMax(): Promise<org_opencv_core_Core$MinMaxLocResult | null>;
    /**
     * @return original return type: 'org.opencv.core.Core$MinMaxLocResult'
     */
    getMinMaxSync(): org_opencv_core_Core$MinMaxLocResult | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var1 original type: 'boolean'
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getModalityLookup(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var1: java_lang_Boolean | boolean): Promise<org_weasis_opencv_data_LookupTableCV | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @param var1 original type: 'boolean'
     * @return original return type: 'org.weasis.opencv.data.LookupTableCV'
     */
    getModalityLookupSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null, var1: java_lang_Boolean | boolean): org_weasis_opencv_data_LookupTableCV | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getDefaultWindow(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): Promise<number>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.WlPresentation'
     * @return original return type: 'double'
     */
    getDefaultWindowSync(var0: org_weasis_opencv_op_lut_WlPresentation | JavaInterfaceProxy<org_weasis_opencv_op_lut_WlPresentationInterface> | null): number;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.PresentationStateLut'
     * @return original return type: 'boolean'
     */
    isPhotometricInterpretationInverse(var0: org_weasis_opencv_op_lut_PresentationStateLut | JavaInterfaceProxy<org_weasis_opencv_op_lut_PresentationStateLutInterface> | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.weasis.opencv.op.lut.PresentationStateLut'
     * @return original return type: 'boolean'
     */
    isPhotometricInterpretationInverseSync(var0: org_weasis_opencv_op_lut_PresentationStateLut | JavaInterfaceProxy<org_weasis_opencv_op_lut_PresentationStateLutInterface> | null): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'org.weasis.opencv.op.lut.LutParameters'
     */
    getLutParameters(var0: java_lang_Boolean | boolean, var1: org_weasis_opencv_data_LookupTableCV | null, var2: java_lang_Boolean | boolean, var3: org_dcm4che3_img_data_PrDicomObject | null): Promise<org_weasis_opencv_op_lut_LutParameters | null>;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'org.weasis.opencv.data.LookupTableCV'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'org.dcm4che3.img.data.PrDicomObject'
     * @return original return type: 'org.weasis.opencv.op.lut.LutParameters'
     */
    getLutParametersSync(var0: java_lang_Boolean | boolean, var1: org_weasis_opencv_data_LookupTableCV | null, var2: java_lang_Boolean | boolean, var3: org_dcm4che3_img_data_PrDicomObject | null): org_weasis_opencv_op_lut_LutParameters | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     */
    constructor(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null);
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @return original return type: 'org.dcm4che3.img.DicomImageAdapter'
     */
    static newInstanceAsync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null): Promise<DicomImageAdapter>;
}
declare const DicomImageAdapter_base: typeof DicomImageAdapterClass;
/**
 * Class org.dcm4che3.img.DicomImageAdapter.
 *
 * This actually imports the java class for further use.
 * The class {@link DicomImageAdapterClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class DicomImageAdapter extends DicomImageAdapter_base {
}
export default DicomImageAdapter;
