import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { PlanarImage as org_weasis_opencv_data_PlanarImage, PlanarImageInterface as org_weasis_opencv_data_PlanarImageInterface } from "./../../weasis/opencv/data/PlanarImage";
import { ImageDescriptor as org_dcm4che3_img_stream_ImageDescriptor } from "./stream/ImageDescriptor";
import { DicomImageReadParam as org_dcm4che3_img_DicomImageReadParam } from "./DicomImageReadParam";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { DicomImageAdapter as org_dcm4che3_img_DicomImageAdapter } from "./DicomImageAdapter";
/**
 * This class just defines types, you should import {@link ImageRendering} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ImageRenderingClass extends JavaClass {
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getRawRenderedImage(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getRawRenderedImageSync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): org_weasis_opencv_data_PlanarImage | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getDefaultRenderedImage(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getDefaultRenderedImageSync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): org_weasis_opencv_data_PlanarImage | null;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getVoiLutImage(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_DicomImageAdapter | null, var2: org_dcm4che3_img_DicomImageReadParam | null): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getVoiLutImageSync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_DicomImageAdapter | null, var2: org_dcm4che3_img_DicomImageReadParam | null): org_weasis_opencv_data_PlanarImage | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getVoiLutImage(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @param var3 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getVoiLutImageSync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: org_dcm4che3_img_DicomImageReadParam | null, var3: java_lang_Integer | number): org_weasis_opencv_data_PlanarImage | null;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getModalityLutImage(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_DicomImageAdapter | null, var2: org_dcm4che3_img_DicomImageReadParam | null): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.DicomImageAdapter'
     * @param var2 original type: 'org.dcm4che3.img.DicomImageReadParam'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getModalityLutImageSync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_DicomImageAdapter | null, var2: org_dcm4che3_img_DicomImageReadParam | null): org_weasis_opencv_data_PlanarImage | null;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getImageWithoutEmbeddedOverlay(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: java_lang_Integer | number): Promise<org_weasis_opencv_data_PlanarImage | null>;
    /**
     * @param var0 original type: 'org.weasis.opencv.data.PlanarImage'
     * @param var1 original type: 'org.dcm4che3.img.stream.ImageDescriptor'
     * @param var2 original type: 'int'
     * @return original return type: 'org.weasis.opencv.data.PlanarImage'
     */
    static getImageWithoutEmbeddedOverlaySync(var0: org_weasis_opencv_data_PlanarImage | JavaInterfaceProxy<org_weasis_opencv_data_PlanarImageInterface> | null, var1: org_dcm4che3_img_stream_ImageDescriptor | null, var2: java_lang_Integer | number): org_weasis_opencv_data_PlanarImage | null;
}
declare const ImageRendering_base: typeof ImageRenderingClass;
/**
 * Class org.dcm4che3.img.ImageRendering.
 *
 * This actually imports the java class for further use.
 * The class {@link ImageRenderingClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ImageRendering extends ImageRendering_base {
}
export default ImageRendering;
