"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Transcoder$Format = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.dcm4che3.img.Transcoder$Format.
 *
 * This actually imports the java class for further use.
 * The class {@link Transcoder$FormatClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Transcoder$Format extends (0, java_bridge_1.importClass)('org.dcm4che3.img.Transcoder$Format') {
}
exports.Transcoder$Format = Transcoder$Format;
exports.default = Transcoder$Format;
