import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Point as org_opencv_core_Point } from "./Point";
import { Double as java_lang_Double } from "./../../../java/lang/Double";
/**
 * This class just defines types, you should import {@link Core$MinMaxLocResult} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Core$MinMaxLocResultClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * Original type: 'org.opencv.core.Point'
     */
    maxLoc: org_opencv_core_Point | null;
    /**
     * Original type: 'double'
     */
    maxVal: java_lang_Double | number;
    /**
     * Original type: 'double'
     */
    minVal: java_lang_Double | number;
    /**
     * Original type: 'org.opencv.core.Point'
     */
    minLoc: org_opencv_core_Point | null;
    constructor();
    /**
     * @return original return type: 'org.opencv.core.Core$MinMaxLocResult'
     */
    static newInstanceAsync(): Promise<Core$MinMaxLocResult>;
}
declare const Core$MinMaxLocResult_base: typeof Core$MinMaxLocResultClass;
/**
 * Class org.opencv.core.Core$MinMaxLocResult.
 *
 * This actually imports the java class for further use.
 * The class {@link Core$MinMaxLocResultClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Core$MinMaxLocResult extends Core$MinMaxLocResult_base {
}
export default Core$MinMaxLocResult;
//# sourceMappingURL=Core$MinMaxLocResult.d.ts.map