"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CvType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.opencv.core.CvType.
 *
 * This actually imports the java class for further use.
 * The class {@link CvTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CvType extends (0, java_bridge_1.importClass)('org.opencv.core.CvType') {
}
exports.CvType = CvType;
exports.default = CvType;
