"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mat$Atable = exports.createMat$AtableProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Mat$Atable} interface.
 * All required methods in {@link Mat$AtableInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMat$AtableProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.opencv.core.Mat$Atable', methods, opts);
}
exports.createMat$AtableProxy = createMat$AtableProxy;
/**
 * Class org.opencv.core.Mat$Atable.
 *
 * This actually imports the java class for further use.
 * The class {@link Mat$AtableClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Mat$Atable extends (0, java_bridge_1.importClass)('org.opencv.core.Mat$Atable') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Mat$Atable = Mat$Atable;
exports.default = Mat$Atable;
