"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mat$Tuple4 = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.opencv.core.Mat$Tuple4.
 *
 * This actually imports the java class for further use.
 * The class {@link Mat$Tuple4Class} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Mat$Tuple4 extends (0, java_bridge_1.importClass)('org.opencv.core.Mat$Tuple4') {
}
exports.Mat$Tuple4 = Mat$Tuple4;
exports.default = Mat$Tuple4;
