import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Class as java_lang_Class } from "./../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../java/lang/Integer";
import { Double as java_lang_Double } from "./../../../java/lang/Double";
/**
 * This class just defines types, you should import {@link Range} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RangeClass extends JavaClass {
    /**
     * @return original return type: 'org.opencv.core.Range'
     */
    static all(): Promise<Range | null>;
    /**
     * @return original return type: 'org.opencv.core.Range'
     */
    static allSync(): Range | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'double[]'
     * @return original return type: 'void'
     */
    set(var0: (java_lang_Double | number)[] | null): Promise<void>;
    /**
     * @param var0 original type: 'double[]'
     * @return original return type: 'void'
     */
    setSync(var0: (java_lang_Double | number)[] | null): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'org.opencv.core.Range'
     */
    shift(var0: java_lang_Integer | number): Promise<Range | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'org.opencv.core.Range'
     */
    shiftSync(var0: java_lang_Integer | number): Range | null;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'boolean'
     */
    empty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    emptySync(): boolean;
    /**
     * @return original return type: 'int'
     */
    size(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    sizeSync(): number;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @param var0 original type: 'org.opencv.core.Range'
     * @return original return type: 'org.opencv.core.Range'
     */
    intersection(var0: RangeClass | null): Promise<Range | null>;
    /**
     * @param var0 original type: 'org.opencv.core.Range'
     * @return original return type: 'org.opencv.core.Range'
     */
    intersectionSync(var0: RangeClass | null): Range | null;
    /**
     * @return original return type: 'org.opencv.core.Range'
     */
    clone(): Promise<Range | null>;
    /**
     * @return original return type: 'org.opencv.core.Range'
     */
    cloneSync(): Range | null;
    /**
     * @return original return type: 'java.lang.Object'
     */
    clone(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    cloneSync(): BasicOrJavaType | null;
    /**
     * Original type: 'int'
     */
    start: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    end: java_lang_Integer | number;
    /**
     * @param var0 original type: 'double[]'
     */
    constructor(var0: (java_lang_Double | number)[] | null);
    /**
     * @param var0 original type: 'double[]'
     * @return original return type: 'org.opencv.core.Range'
     */
    static newInstanceAsync(var0: (java_lang_Double | number)[] | null): Promise<Range>;
    constructor();
    /**
     * @return original return type: 'org.opencv.core.Range'
     */
    static newInstanceAsync(): Promise<Range>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     */
    constructor(var0: java_lang_Integer | number, var1: java_lang_Integer | number);
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'int'
     * @return original return type: 'org.opencv.core.Range'
     */
    static newInstanceAsync(var0: java_lang_Integer | number, var1: java_lang_Integer | number): Promise<Range>;
}
declare const Range_base: typeof RangeClass;
/**
 * Class org.opencv.core.Range.
 *
 * This actually imports the java class for further use.
 * The class {@link RangeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Range extends Range_base {
}
export default Range;
