"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Range = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.opencv.core.Range.
 *
 * This actually imports the java class for further use.
 * The class {@link RangeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Range extends (0, java_bridge_1.importClass)('org.opencv.core.Range') {
}
exports.Range = Range;
exports.default = Range;
