"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServiceRegistry$Filter = exports.createServiceRegistry$FilterProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ServiceRegistry$Filter} interface.
 * All required methods in {@link ServiceRegistry$FilterInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createServiceRegistry$FilterProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('javax.imageio.spi.ServiceRegistry$Filter', methods, opts);
}
exports.createServiceRegistry$FilterProxy = createServiceRegistry$FilterProxy;
/**
 * Class javax.imageio.spi.ServiceRegistry$Filter.
 *
 * This actually imports the java class for further use.
 * The class {@link ServiceRegistry$FilterClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ServiceRegistry$Filter extends (0, java_bridge_1.importClass)('javax.imageio.spi.ServiceRegistry$Filter') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ServiceRegistry$Filter = ServiceRegistry$Filter;
exports.default = ServiceRegistry$Filter;
