"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MPPSScpInject = void 0;
exports.createMPPSScpInjectProxy = createMPPSScpInjectProxy;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link MPPSScpInject} interface.
 * All required methods in {@link MPPSScpInjectInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createMPPSScpInjectProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.github.chinlinlee.dcm777.net.MPPSScpInject', methods, opts);
}
/**
 * Class org.github.chinlinlee.dcm777.net.MPPSScpInject.
 *
 * This actually imports the java class for further use.
 * The class {@link MPPSScpInjectClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class MPPSScpInject extends (0, java_bridge_1.importClass)('org.github.chinlinlee.dcm777.net.MPPSScpInject') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.MPPSScpInject = MPPSScpInject;
exports.default = MPPSScpInject;
